USE DATABASE SNOW_VALUT;
USE SCHEMA ANALYTICAL;

CREATE OR REPLACE VIEW VW_PATIENT_360 AS
SELECT 
    dp.PATIENT_ID,
    dp.NAME,
    dp.GENDER,
    dp.CITY,
    COUNT(DISTINCT fa.APPOINTMENT_ID) AS TOTAL_APPOINTMENTS,
    COUNT(DISTINCT fmr.RECORD_ID) AS TOTAL_RECORDS,
    SUM(fb.TOTAL_AMOUNT) AS TOTAL_BILL,
    SUM(fb.PAID_AMOUNT) AS TOTAL_PAID
FROM CURATED.DIM_PATIENT dp
LEFT JOIN CURATED.FACT_APPOINTMENTS fa 
    ON dp.PATIENT_KEY = fa.PATIENT_KEY
LEFT JOIN CURATED.FACT_MEDICAL_RECORDS fmr 
    ON dp.PATIENT_KEY = fmr.PATIENT_KEY
LEFT JOIN CURATED.FACT_BILLING fb 
    ON dp.PATIENT_KEY = fb.PATIENT_KEY
WHERE dp.IS_CURRENT = 'Y'
GROUP BY dp.PATIENT_ID, dp.NAME, dp.GENDER, dp.CITY;

CREATE OR REPLACE VIEW VW_PATIENT_RISK AS
SELECT 
    dp.PATIENT_ID,
    dp.NAME,
    COUNT(fmr.RECORD_ID) AS MEDICAL_HISTORY,
    
    CASE 
        WHEN COUNT(fmr.RECORD_ID) > 5 THEN 'HIGH RISK'
        WHEN COUNT(fmr.RECORD_ID) BETWEEN 2 AND 5 THEN 'MEDIUM RISK'
        ELSE 'LOW RISK'
    END AS RISK_LEVEL
FROM CURATED.DIM_PATIENT dp
LEFT JOIN CURATED.FACT_MEDICAL_RECORDS fmr 
    ON dp.PATIENT_KEY = fmr.PATIENT_KEY
WHERE dp.IS_CURRENT = 'Y'
GROUP BY dp.PATIENT_ID, dp.NAME;

CREATE OR REPLACE VIEW VW_REVENUE_TRENDS AS
SELECT 
    DATE_TRUNC('MONTH', BILL_DATE) AS MONTH,
    SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE,
    SUM(PAID_AMOUNT) AS TOTAL_PAID
FROM CURATED.FACT_BILLING
GROUP BY DATE_TRUNC('MONTH', BILL_DATE);

CREATE OR REPLACE VIEW VW_NO_SHOW_ANALYSIS AS
SELECT 
    STATUS,
    COUNT(*) AS TOTAL,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 2) AS PERCENTAGE
FROM CURATED.FACT_APPOINTMENTS
GROUP BY STATUS;

SELECT * FROM ANALYTICAL.VW_PATIENT_360;
SELECT * FROM ANALYTICAL.VW_PATIENT_RISK WHERE RISK_LEVEL='MEDIUM RISK';
SELECT * FROM ANALYTICAL.VW_REVENUE_TRENDS;
SELECT * FROM ANALYTICAL.VW_NO_SHOW_ANALYSIS;

DROP ANALYTICAL.VW_PATIENT_360






CREATE OR REPLACE VIEW ANALYTICAL.VW_PATIENT_360 AS
SELECT 
    dp.PATIENT_ID,
    dp.NAME,
    dp.GENDER,
    dp.CITY,

    COALESCE(fa.TOTAL_APPOINTMENTS, 0) AS TOTAL_APPOINTMENTS,
    COALESCE(fmr.TOTAL_RECORDS, 0) AS TOTAL_RECORDS,
    COALESCE(fb.TOTAL_BILL, 0) AS TOTAL_BILL,
    COALESCE(fb.TOTAL_PAID, 0) AS TOTAL_PAID

FROM CURATED.DIM_PATIENT dp

-- ✅ APPOINTMENTS (DEDUP + SAFE)
LEFT JOIN (
    SELECT 
        PATIENT_KEY,
        COUNT(DISTINCT APPOINTMENT_ID) AS TOTAL_APPOINTMENTS
    FROM CURATED.FACT_APPOINTMENTS
    WHERE IS_VALID_RECORD = TRUE
      AND PATIENT_KEY IS NOT NULL
    GROUP BY PATIENT_KEY
) fa 
ON dp.PATIENT_KEY = fa.PATIENT_KEY

-- ✅ MEDICAL RECORDS
LEFT JOIN (
    SELECT 
        PATIENT_KEY,
        COUNT(DISTINCT RECORD_ID) AS TOTAL_RECORDS
    FROM CURATED.FACT_MEDICAL_RECORDS
    WHERE IS_VALID_RECORD = TRUE
      AND PATIENT_KEY IS NOT NULL
    GROUP BY PATIENT_KEY
) fmr 
ON dp.PATIENT_KEY = fmr.PATIENT_KEY

-- ✅ BILLING (FIX NEGATIVE + NULL)
LEFT JOIN (
    SELECT 
        PATIENT_KEY,
        SUM(
            CASE 
                WHEN TOTAL_AMOUNT IS NULL OR TOTAL_AMOUNT < 0 THEN 0 
                ELSE TOTAL_AMOUNT 
            END
        ) AS TOTAL_BILL,

        SUM(
Selection deleted

            CASE 
                WHEN PAID_AMOUNT IS NULL OR PAID_AMOUNT < 0 THEN 0 
                ELSE PAID_AMOUNT 
            END
        ) AS TOTAL_PAID

    FROM CURATED.FACT_BILLING
    WHERE IS_VALID_RECORD = TRUE
      AND PATIENT_KEY IS NOT NULL
    GROUP BY PATIENT_KEY
) fb 
ON dp.PATIENT_KEY = fb.PATIENT_KEY

WHERE dp.IS_CURRENT = 'Y';

select * from ANALYTICAL.VW_PATIENT_360



SELECT * FROM ANALYTICAL.VW_NO_SHOW_ANALYSIS;

SELECT * From VW_PATIENT_360
WHERE CITY='Hyderabad'