-- =============================================================
-- STEP 1: USE DATABASE / SCHEMAS / WAREHOUSE
-- =============================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE SNOW_VALUT;
USE SCHEMA RAW;

-- =============================================================
-- STEP 2: CREATE STREAMS ON RAW TABLES
-- =============================================================

CREATE OR REPLACE STREAM STRM_RAW_PATIENTS
ON TABLE RAW.RAW_PATIENTS;

CREATE OR REPLACE STREAM STRM_RAW_APPOINTMENTS
ON TABLE RAW.RAW_APPOINTMENTS;

CREATE OR REPLACE STREAM STRM_RAW_MEDICAL_RECORDS
ON TABLE RAW.RAW_MEDICAL_RECORDS;

CREATE OR REPLACE STREAM STRM_RAW_BILLING
ON TABLE RAW.RAW_BILLING;

-- =============================================================
-- STEP 3: VERIFY STREAMS
-- =============================================================

SHOW STREAMS;

-- =============================================================
-- STEP 4: CREATE TASK FOR PATIENTS
-- =============================================================

CREATE OR REPLACE TASK TASK_VALIDATE_PATIENTS
WAREHOUSE = COMPUTE_WH
SCHEDULE = '10 seconds'
WHEN SYSTEM$STREAM_HAS_DATA('RAW.STRM_RAW_PATIENTS')
AS

MERGE INTO VALIDATED.VALIDATED_PATIENTS AS T
USING
(
    SELECT
        TRIM(PATIENT_ID) AS PATIENT_ID,
        INITCAP(TRIM(NAME)) AS NAME,
        TRY_TO_DATE(DOB) AS DOB,
        UPPER(TRIM(GENDER)) AS GENDER,
        LOWER(TRIM(EMAIL)) AS EMAIL,
        REGEXP_REPLACE(PHONE,'[^0-9]','') AS PHONE,
        INITCAP(TRIM(CITY)) AS CITY,
        UPPER(TRIM(STATE)) AS STATE,
        TRUE AS IS_VALID_RECORD,
        'AUTO_LOAD' AS VALIDATION_ERRORS,
        CURRENT_USER() AS CREATED_BY,
        CURRENT_TIMESTAMP() AS CREATED_ON
    FROM RAW.STRM_RAW_PATIENTS
) S
ON T.PATIENT_ID = S.PATIENT_ID

WHEN MATCHED THEN UPDATE SET
T.NAME = S.NAME,
T.DOB = S.DOB,
T.GENDER = S.GENDER,
T.EMAIL = S.EMAIL,
T.PHONE = S.PHONE,
T.CITY = S.CITY,
T.STATE = S.STATE,
T.IS_VALID_RECORD = TRUE,
T.VALIDATION_ERRORS = 'AUTO_UPDATED',
T.CREATED_ON = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN INSERT
(
PATIENT_ID, NAME, DOB, GENDER, EMAIL, PHONE, CITY, STATE,
IS_VALID_RECORD, VALIDATION_ERRORS, CREATED_BY, CREATED_ON
)
VALUES
(
S.PATIENT_ID, S.NAME, S.DOB, S.GENDER, S.EMAIL, S.PHONE, S.CITY, S.STATE,
S.IS_VALID_RECORD, S.VALIDATION_ERRORS, S.CREATED_BY, S.CREATED_ON
);


ALTER TASK TASK_VALIDATE_PATIENTS RESUME;



INSERT INTO RAW.RAW_PATIENTS
(
PATIENT_ID, NAME, DOB, GENDER, EMAIL, PHONE, CITY, STATE
)
VALUES
(
'P1101',
'New Patient',
'2000-01-01',
'FEMALE',
'newpatient@test.com',
'9876543210',
'Chennai',
'TN'
);

-- WAIT 10 sec MINUTES
-- THEN CHECK:

select * from raw.strm_raw_patients;

SELECT * FROM VALIDATED.VALIDATED_PATIENTS
WHERE PATIENT_ID = 'P1101';

show tasks;
-- =============================================================
-- STEP 5: CREATE TASK FOR APPOINTMENTS
-- =============================================================

CREATE OR REPLACE TASK TASK_VALIDATE_APPOINTMENTS
WAREHOUSE = COMPUTE_WH
SCHEDULE = '10 seconds'
WHEN SYSTEM$STREAM_HAS_DATA('RAW.STRM_RAW_APPOINTMENTS')
AS

MERGE INTO VALIDATED.VALIDATED_APPOINTMENTS AS T
USING
(
    SELECT
        TRIM(APPOINTMENT_ID) AS APPOINTMENT_ID,
        TRIM(PATIENT_ID) AS PATIENT_ID,
        INITCAP(TRIM(DOCTOR)) AS DOCTOR,
        INITCAP(TRIM(DEPARTMENT)) AS DEPARTMENT,
        TRY_TO_DATE(APPOINTMENT_DATE) AS APPOINTMENT_DATE,
        UPPER(TRIM(STATUS)) AS STATUS,
        TRUE AS IS_VALID_RECORD,
        'AUTO_LOAD' AS VALIDATION_ERRORS,
        CURRENT_USER() AS CREATED_BY,
        CURRENT_TIMESTAMP() AS CREATED_ON
    FROM RAW.STRM_RAW_APPOINTMENTS
) S
ON T.APPOINTMENT_ID = S.APPOINTMENT_ID

WHEN MATCHED THEN UPDATE SET
T.STATUS = S.STATUS,
T.APPOINTMENT_DATE = S.APPOINTMENT_DATE,
T.CREATED_ON = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN INSERT
(
APPOINTMENT_ID, PATIENT_ID, DOCTOR, DEPARTMENT, APPOINTMENT_DATE, STATUS,
IS_VALID_RECORD, VALIDATION_ERRORS, CREATED_BY, CREATED_ON
)
VALUES
(
S.APPOINTMENT_ID, S.PATIENT_ID, S.DOCTOR, S.DEPARTMENT, S.APPOINTMENT_DATE, S.STATUS,
S.IS_VALID_RECORD, S.VALIDATION_ERRORS, S.CREATED_BY, S.CREATED_ON
);

-- =============================================================
-- STEP 6: CREATE TASK FOR MEDICAL RECORDS
-- =============================================================

CREATE OR REPLACE TASK TASK_VALIDATE_MEDICAL
WAREHOUSE = COMPUTE_WH
SCHEDULE = '10 seconds'
WHEN SYSTEM$STREAM_HAS_DATA('RAW.STRM_RAW_MEDICAL_RECORDS')
AS

MERGE INTO VALIDATED.VALIDATED_MEDICAL_RECORDS AS T
USING
(
    SELECT
        TRIM(RECORD_ID) AS RECORD_ID,
        TRIM(PATIENT_ID) AS PATIENT_ID,
        TRY_TO_DATE(RECORD_DATE) AS RECORD_DATE,
        INITCAP(TRIM(DIAGNOSIS)) AS DIAGNOSIS,
        INITCAP(TRIM(PROCEDURE)) AS PROCEDURE,
        TRUE AS IS_VALID_RECORD,
        'AUTO_LOAD' AS VALIDATION_ERRORS,
        CURRENT_USER() AS CREATED_BY,
        CURRENT_TIMESTAMP() AS CREATED_ON
    FROM RAW.STRM_RAW_MEDICAL_RECORDS
) S
ON T.RECORD_ID = S.RECORD_ID

WHEN MATCHED THEN UPDATE SET
T.DIAGNOSIS = S.DIAGNOSIS,
T.PROCEDURE = S.PROCEDURE,
T.CREATED_ON = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN INSERT
(
RECORD_ID, PATIENT_ID, RECORD_DATE, DIAGNOSIS, PROCEDURE,
IS_VALID_RECORD, VALIDATION_ERRORS, CREATED_BY, CREATED_ON
)
VALUES
(
S.RECORD_ID, S.PATIENT_ID, S.RECORD_DATE, S.DIAGNOSIS, S.PROCEDURE,
S.IS_VALID_RECORD, S.VALIDATION_ERRORS, S.CREATED_BY, S.CREATED_ON
);

-- =============================================================
-- STEP 7: CREATE TASK FOR BILLING
-- =============================================================

CREATE OR REPLACE TASK TASK_VALIDATE_BILLING
WAREHOUSE = COMPUTE_WH
SCHEDULE = '10 seconds'
WHEN SYSTEM$STREAM_HAS_DATA('RAW.STRM_RAW_BILLING')
AS

MERGE INTO VALIDATED.VALIDATED_BILLING AS T
USING
(
    SELECT
        TRIM(BILL_ID) AS BILL_ID,
        TRIM(PATIENT_ID) AS PATIENT_ID,
        TRIM(APPOINTMENT_ID) AS APPOINTMENT_ID,
        TRY_TO_DATE(BILL_DATE) AS BILL_DATE,
        TRY_TO_NUMBER(REPLACE(TOTAL_AMOUNT,',','')) AS TOTAL_AMOUNT,
        TRY_TO_NUMBER(REPLACE(PAID_AMOUNT,',','')) AS PAID_AMOUNT,
        UPPER(TRIM(PAYMENT_STATUS)) AS PAYMENT_STATUS,
        TRUE AS IS_VALID_RECORD,
        'AUTO_LOAD' AS VALIDATION_ERRORS,
        CURRENT_USER() AS CREATED_BY,
        CURRENT_TIMESTAMP() AS CREATED_ON
    FROM RAW.STRM_RAW_BILLING
) S
ON T.BILL_ID = S.BILL_ID

WHEN MATCHED THEN UPDATE SET
T.TOTAL_AMOUNT = S.TOTAL_AMOUNT,
T.PAID_AMOUNT = S.PAID_AMOUNT,
T.PAYMENT_STATUS = S.PAYMENT_STATUS,
T.CREATED_ON = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN INSERT
(
BILL_ID, PATIENT_ID, APPOINTMENT_ID, BILL_DATE, TOTAL_AMOUNT, PAID_AMOUNT, PAYMENT_STATUS,
IS_VALID_RECORD, VALIDATION_ERRORS, CREATED_BY, CREATED_ON
)
VALUES
(
S.BILL_ID, S.PATIENT_ID, S.APPOINTMENT_ID, S.BILL_DATE, S.TOTAL_AMOUNT, S.PAID_AMOUNT, S.PAYMENT_STATUS,
S.IS_VALID_RECORD, S.VALIDATION_ERRORS, S.CREATED_BY, S.CREATED_ON
);

-- =============================================================
-- STEP 8: RESUME ALL TASKS
-- =============================================================

ALTER TASK TASK_VALIDATE_PATIENTS RESUME;
ALTER TASK TASK_VALIDATE_APPOINTMENTS RESUME;
ALTER TASK TASK_VALIDATE_MEDICAL RESUME;
ALTER TASK TASK_VALIDATE_BILLING RESUME;

-- =============================================================
-- STEP 9: CHECK TASK STATUS
-- =============================================================

SHOW TASKS;

-- =============================================================
-- STEP 10: TEST AUTOMATION
-- INSERT NEW RAW DATA
-- =============================================================

INSERT INTO RAW.RAW_PATIENTS
(
PATIENT_ID, NAME, DOB, GENDER, EMAIL, PHONE, CITY, STATE
)
VALUES
(
'P999',
'New Patient',
'2000-01-01',
'FEMALE',
'newpatient@test.com',
'9876543210',
'Chennai',
'TN'
);

-- WAIT 10 sec MINUTES
-- THEN CHECK:


select * from raw.strm_raw_patients;

SELECT * FROM VALIDATED.VALIDATED_PATIENTS
WHERE PATIENT_ID = 'P999';


show tasks;

-- =====================================================
-- 3.medical_records
-- =====================================================
INSERT INTO RAW.RAW_MEDICAL_RECORDS
(
RECORD_ID, PATIENT_ID, RECORD_DATE, DIAGNOSIS, PROCEDURE
)
VALUES
(
'M1000',
'P999',
'2026-04-30',
'Chest Pain',
'ECG'
);

-- CHECK STREAM
SELECT * FROM RAW.STRM_RAW_MEDICAL_RECORDS;

-- WAIT 10 sec MINUTES THEN CHECK VALIDATED
SELECT *
FROM VALIDATED.VALIDATED_MEDICAL_RECORDS
WHERE RECORD_ID = 'M999';



-- =====================================================
-- 3. BILLING
-- =====================================================

INSERT INTO RAW.RAW_BILLING
(
BILL_ID, PATIENT_ID, APPOINTMENT_ID, BILL_DATE,
TOTAL_AMOUNT, PAID_AMOUNT, PAYMENT_STATUS
)
VALUES
(
'B999',
'P999',
'A999',
'2026-04-30',
'2500',
'1000',
'PARTIAL'
);

-- CHECK STREAM
SELECT * FROM RAW.STRM_RAW_BILLING;

-- WAIT 5 MINUTES THEN CHECK VALIDATED
SELECT *
FROM VALIDATED.VALIDATED_BILLING
WHERE BILL_ID = 'B999';

-- =============================================================
-- STEP 11: TASK HISTORY
-- =============================================================

SELECT *
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY());

-- =============================================================
-- END
-- =============================================================



USE DATABASE SNOW_VALUT;
USE SCHEMA VALIDATED;

CREATE OR REPLACE STREAM st_patients 
ON TABLE VALIDATED_PATIENTS;

CREATE OR REPLACE STREAM st_appointments 
ON TABLE VALIDATED_APPOINTMENTS;

CREATE OR REPLACE STREAM st_billing 
ON TABLE VALIDATED_BILLING;

CREATE OR REPLACE STREAM st_medical_records 
ON TABLE VALIDATED_MEDICAL_RECORDS;


USE DATABASE SNOW_VALUT;
USE SCHEMA CURATED;

CREATE OR REPLACE PROCEDURE SP_LOAD_CURATED()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN

-- =============================================
-- DIM_PATIENT (SCD TYPE 2)
-- =============================================

MERGE INTO DIM_PATIENT tgt
USING (
    SELECT *
    FROM VALIDATED.ST_PATIENTS
    WHERE METADATA$ACTION IN ('INSERT','UPDATE')
) src
ON tgt.PATIENT_ID = src.PATIENT_ID AND tgt.IS_CURRENT = 'Y'

WHEN MATCHED AND (
    tgt.NAME != src.NAME OR
    tgt.CITY != src.CITY OR
    tgt.STATE != src.STATE OR
    tgt.PHONE != src.PHONE OR
    tgt.EMAIL != src.EMAIL
)
THEN UPDATE SET
    tgt.IS_CURRENT = 'N',
    tgt.VALID_TO = CURRENT_DATE()

WHEN NOT MATCHED THEN INSERT (
    PATIENT_ID, NAME, DOB, GENDER, EMAIL, PHONE, CITY, STATE,
    VALID_FROM, VALID_TO, IS_CURRENT, VERSION_NUMBER,
    CREATED_BY, CREATED_ON, SOURCE_TABLE
)
VALUES (
    src.PATIENT_ID, src.NAME, src.DOB, src.GENDER, src.EMAIL, src.PHONE,
    src.CITY, src.STATE,
    CURRENT_DATE(), TO_DATE('9999-12-31'), 'Y',
    1,
    CURRENT_USER(), CURRENT_TIMESTAMP(), 'VALIDATED_PATIENTS'
);

-- =============================================
-- DIM_DOCTOR (SCD TYPE 2)
-- =============================================

MERGE INTO DIM_DOCTOR tgt
USING (
    SELECT DISTINCT
        DOCTOR AS DOCTOR_ID,
        DOCTOR AS DOCTOR_NAME,
        DEPARTMENT AS SPECIALIZATION,
        DEPARTMENT
    FROM VALIDATED.ST_APPOINTMENTS
    WHERE METADATA$ACTION IN ('INSERT','UPDATE')
) src
ON tgt.DOCTOR_ID = src.DOCTOR_ID AND tgt.IS_CURRENT = 'Y'

WHEN MATCHED AND (
    tgt.DOCTOR_NAME != src.DOCTOR_NAME OR
    tgt.SPECIALIZATION != src.SPECIALIZATION OR
    tgt.DEPARTMENT != src.DEPARTMENT
)
THEN UPDATE SET
    tgt.IS_CURRENT = 'N',
    tgt.VALID_TO = CURRENT_DATE()

WHEN NOT MATCHED THEN INSERT (
    DOCTOR_ID, DOCTOR_NAME, SPECIALIZATION, DEPARTMENT,
    VALID_FROM, VALID_TO, IS_CURRENT, VERSION_NUMBER,
    CREATED_BY, CREATED_ON, SOURCE_TABLE
)
VALUES (
    src.DOCTOR_ID, src.DOCTOR_NAME, src.SPECIALIZATION, src.DEPARTMENT,
    CURRENT_DATE(), TO_DATE('9999-12-31'), 'Y',
    1,
    CURRENT_USER(), CURRENT_TIMESTAMP(), 'VALIDATED_APPOINTMENTS'
);

-- =============================================
-- DIM_DEPARTMENT
-- =============================================

MERGE INTO DIM_DEPARTMENT tgt
USING (
    SELECT DISTINCT
        UPPER(SUBSTR(DEPARTMENT,1,4)) AS DEPT_CODE,
        INITCAP(DEPARTMENT) AS DEPT_NAME
    FROM VALIDATED.ST_APPOINTMENTS
    WHERE METADATA$ACTION IN ('INSERT','UPDATE')
) src
ON tgt.DEPT_CODE = src.DEPT_CODE

WHEN MATCHED THEN UPDATE SET
    tgt.DEPT_NAME = src.DEPT_NAME

WHEN NOT MATCHED THEN INSERT (
    DEPT_CODE, DEPT_NAME, CREATED_BY, CREATED_ON
)
VALUES (
    src.DEPT_CODE, src.DEPT_NAME, CURRENT_USER(), CURRENT_TIMESTAMP()
);

-- =============================================
-- FACT_APPOINTMENTS
-- =============================================

MERGE INTO FACT_APPOINTMENTS tgt
USING (
    SELECT 
        A.APPOINTMENT_ID,
        dp.PATIENT_KEY,
        dd.DOCTOR_KEY,
        dpt.DEPT_KEY,
        A.APPOINTMENT_DATE,
        A.STATUS,
        A.IS_VALID_RECORD
    FROM VALIDATED.ST_APPOINTMENTS A
    LEFT JOIN DIM_PATIENT dp 
        ON A.PATIENT_ID = dp.PATIENT_ID AND dp.IS_CURRENT = 'Y'
    LEFT JOIN DIM_DOCTOR dd 
        ON A.DOCTOR = dd.DOCTOR_ID AND dd.IS_CURRENT = 'Y'
    LEFT JOIN DIM_DEPARTMENT dpt 
        ON UPPER(SUBSTR(A.DEPARTMENT,1,4)) = dpt.DEPT_CODE
    WHERE METADATA$ACTION IN ('INSERT','UPDATE')
) src
ON tgt.APPOINTMENT_ID = src.APPOINTMENT_ID

WHEN MATCHED THEN UPDATE SET
    tgt.PATIENT_KEY = src.PATIENT_KEY,
    tgt.DOCTOR_KEY = src.DOCTOR_KEY,
    tgt.DEPT_KEY = src.DEPT_KEY,
    tgt.APPOINTMENT_DATE = src.APPOINTMENT_DATE,
    tgt.STATUS = src.STATUS,
    tgt.IS_VALID_RECORD = src.IS_VALID_RECORD

WHEN NOT MATCHED THEN INSERT (
    APPOINTMENT_ID, PATIENT_KEY, DOCTOR_KEY, DEPT_KEY,
    APPOINTMENT_DATE, STATUS, IS_VALID_RECORD,
    CREATED_BY, CREATED_ON
)
VALUES (
    src.APPOINTMENT_ID, src.PATIENT_KEY, src.DOCTOR_KEY, src.DEPT_KEY,
    src.APPOINTMENT_DATE, src.STATUS, src.IS_VALID_RECORD,
    CURRENT_USER(), CURRENT_TIMESTAMP()
);

-- =============================================
-- FACT_MEDICAL_RECORDS
-- =============================================

MERGE INTO FACT_MEDICAL_RECORDS tgt
USING (
    SELECT 
        M.RECORD_ID,
        dp.PATIENT_KEY,
        M.RECORD_DATE,
        M.DIAGNOSIS,
        M.PROCEDURE AS PROCEDURE_NAME,
        M.IS_VALID_RECORD
    FROM VALIDATED.ST_MEDICAL_RECORDS M
    LEFT JOIN DIM_PATIENT dp 
        ON M.PATIENT_ID = dp.PATIENT_ID AND dp.IS_CURRENT = 'Y'
    WHERE METADATA$ACTION IN ('INSERT','UPDATE')
) src
ON tgt.RECORD_ID = src.RECORD_ID

WHEN MATCHED THEN UPDATE SET
    tgt.PATIENT_KEY = src.PATIENT_KEY,
    tgt.RECORD_DATE = src.RECORD_DATE,
    tgt.DIAGNOSIS = src.DIAGNOSIS,
    tgt.PROCEDURE_NAME = src.PROCEDURE_NAME,
    tgt.IS_VALID_RECORD = src.IS_VALID_RECORD

WHEN NOT MATCHED THEN INSERT (
    RECORD_ID, PATIENT_KEY, RECORD_DATE,
    DIAGNOSIS, PROCEDURE_NAME, IS_VALID_RECORD,
    CREATED_BY, CREATED_ON
)
VALUES (
    src.RECORD_ID, src.PATIENT_KEY, src.RECORD_DATE,
    src.DIAGNOSIS, src.PROCEDURE_NAME, src.IS_VALID_RECORD,
    CURRENT_USER(), CURRENT_TIMESTAMP()
);

-- =============================================
-- FACT_BILLING
-- =============================================

MERGE INTO FACT_BILLING tgt
USING (
    SELECT 
        B.BILL_ID,
        dp.PATIENT_KEY,
        fa.APPOINTMENT_KEY,
        B.BILL_DATE,
        B.TOTAL_AMOUNT,
        B.PAID_AMOUNT,
        B.PAYMENT_STATUS,
        B.IS_VALID_RECORD
    FROM VALIDATED.ST_BILLING B
    LEFT JOIN DIM_PATIENT dp 
        ON B.PATIENT_ID = dp.PATIENT_ID AND dp.IS_CURRENT = 'Y'
    LEFT JOIN FACT_APPOINTMENTS fa 
        ON B.APPOINTMENT_ID = fa.APPOINTMENT_ID
    WHERE METADATA$ACTION IN ('INSERT','UPDATE')
) src
ON tgt.BILL_ID = src.BILL_ID

WHEN MATCHED THEN UPDATE SET
    tgt.PATIENT_KEY = src.PATIENT_KEY,
    tgt.APPOINTMENT_KEY = src.APPOINTMENT_KEY,
    tgt.BILL_DATE = src.BILL_DATE,
    tgt.TOTAL_AMOUNT = src.TOTAL_AMOUNT,
    tgt.PAID_AMOUNT = src.PAID_AMOUNT,
    tgt.PAYMENT_STATUS = src.PAYMENT_STATUS,
    tgt.IS_VALID_RECORD = src.IS_VALID_RECORD

WHEN NOT MATCHED THEN INSERT (
    BILL_ID, PATIENT_KEY, APPOINTMENT_KEY,
    BILL_DATE, TOTAL_AMOUNT, PAID_AMOUNT,
    PAYMENT_STATUS, IS_VALID_RECORD,
    CREATED_BY, CREATED_ON
)
VALUES (
    src.BILL_ID, src.PATIENT_KEY, src.APPOINTMENT_KEY,
    src.BILL_DATE, src.TOTAL_AMOUNT, src.PAID_AMOUNT,
    src.PAYMENT_STATUS, src.IS_VALID_RECORD,
    CURRENT_USER(), CURRENT_TIMESTAMP()
);

RETURN 'SUCCESS';

END;
$$;



USE SCHEMA TASKS;

CREATE OR REPLACE TASK TASK_VALIDATED_TO_CURATED
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN
    SYSTEM$STREAM_HAS_DATA('SNOW_VALUT.VALIDATED.ST_PATIENTS')
 OR SYSTEM$STREAM_HAS_DATA('SNOW_VALUT.VALIDATED.ST_APPOINTMENTS')
 OR SYSTEM$STREAM_HAS_DATA('SNOW_VALUT.VALIDATED.ST_MEDICAL_RECORDS')
 OR SYSTEM$STREAM_HAS_DATA('SNOW_VALUT.VALIDATED.ST_BILLING')
AS
CALL CURATED.SP_LOAD_CURATED();

ALTER TASK TASK_VALIDATED_TO_CURATED RESUME;


SELECT *
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY())
WHERE NAME = 'TASK_VALIDATED_TO_CURATED'
ORDER BY SCHEDULED_TIME DESC;

INSERT INTO VALIDATED.VALIDATED_PATIENTS
VALUES (
    'P_TESTT',
    'TEST USER',
    '1995-01-01',
    'M',
    'test@mail.com',
    '9999999999',
    'CHENNAI',
    'TN',
    TRUE,
    'VALID',
    'SYS',
    CURRENT_TIMESTAMP()
);

SELECT SYSTEM$STREAM_HAS_DATA('SNOW_VALUT.VALIDATED.ST_PATIENTS');

SELECT *
FROM CURATED.DIM_PATIENT
WHERE PATIENT_ID = 'P_TESTT';

SELECT *
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY())
WHERE NAME = 'TASK_VALIDATED_TO_CURATED';

