USE SCHEMA CURATED;

-- =============================================
-- 1. DIM_PATIENT (SCD TYPE 2)
-- =============================================
CREATE OR REPLACE TABLE DIM_PATIENT (
    PATIENT_KEY      NUMBER AUTOINCREMENT,
    PATIENT_ID       STRING NOT NULL,
    NAME             STRING,
    DOB              DATE,
    GENDER           STRING,
    EMAIL            STRING,
    PHONE            STRING,
    CITY             STRING,
    STATE            STRING,
    
    -- SCD Type 2 Columns
    VALID_FROM       DATE DEFAULT CURRENT_DATE(),
    VALID_TO         DATE DEFAULT TO_DATE('9999-12-31', 'YYYY-MM-DD'),
    IS_CURRENT       STRING DEFAULT 'Y',
    VERSION_NUMBER   NUMBER DEFAULT 1,
    
    -- Audit
    CREATED_BY       STRING DEFAULT CURRENT_USER(),
    CREATED_ON       TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_TABLE     STRING
);

-- =============================================
-- 2. DIM_DOCTOR (SCD TYPE 2)
-- =============================================
CREATE OR REPLACE TABLE DIM_DOCTOR (
    DOCTOR_KEY       NUMBER AUTOINCREMENT,
    DOCTOR_ID        STRING NOT NULL,
    DOCTOR_NAME      STRING,
    SPECIALIZATION   STRING,
    DEPARTMENT       STRING,
    
    -- SCD Type 2 Columns
    VALID_FROM       DATE DEFAULT CURRENT_DATE(),
    VALID_TO         DATE DEFAULT TO_DATE('9999-12-31', 'YYYY-MM-DD'),
    IS_CURRENT       STRING DEFAULT 'Y',
    VERSION_NUMBER   NUMBER DEFAULT 1,
    
    -- Audit
    CREATED_BY       STRING DEFAULT CURRENT_USER(),
    CREATED_ON       TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_TABLE     STRING
);

-- =============================================
-- 3. DIM_DATE (Static - No SCD)
-- =============================================
CREATE OR REPLACE TABLE DIM_DATE (
    DATE_KEY         NUMBER PRIMARY KEY,
    FULL_DATE        DATE,
    YEAR_NUM         NUMBER,
    MONTH_NUM        NUMBER,
    MONTH_NAME       STRING,
    DAY_NAME         STRING,
    IS_WEEKEND       STRING
);

-- =============================================
-- 4. DIM_DEPARTMENT (Lookup - No SCD)
-- =============================================
CREATE OR REPLACE TABLE DIM_DEPARTMENT (
    DEPT_KEY         NUMBER AUTOINCREMENT,
    DEPT_CODE        STRING,
    DEPT_NAME        STRING,
    CREATED_BY       STRING DEFAULT CURRENT_USER(),
    CREATED_ON       TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- =============================================
-- 5. FACT_APPOINTMENTS
-- =============================================
CREATE OR REPLACE TABLE FACT_APPOINTMENTS (
    APPOINTMENT_KEY  NUMBER AUTOINCREMENT,
    APPOINTMENT_ID   STRING,
    PATIENT_KEY      NUMBER,
    DOCTOR_KEY       NUMBER,
    DEPT_KEY         NUMBER,
    DATE_KEY         NUMBER,
    APPOINTMENT_DATE DATE,
    STATUS           STRING,
    IS_VALID_RECORD  BOOLEAN,
    CREATED_BY       STRING DEFAULT CURRENT_USER(),
    CREATED_ON       TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- =============================================
-- 6. FACT_MEDICAL_RECORDS
-- =============================================
CREATE OR REPLACE TABLE FACT_MEDICAL_RECORDS (
    RECORD_KEY       NUMBER AUTOINCREMENT,
    RECORD_ID        STRING,
    PATIENT_KEY      NUMBER,
    RECORD_DATE      DATE,
    DIAGNOSIS        STRING,
    PROCEDURE_NAME   STRING,
    IS_VALID_RECORD  BOOLEAN,
    CREATED_BY       STRING DEFAULT CURRENT_USER(),
    CREATED_ON       TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- =============================================
-- 7. FACT_BILLING
-- =============================================
CREATE OR REPLACE TABLE FACT_BILLING (
    BILL_KEY         NUMBER AUTOINCREMENT,
    BILL_ID          STRING,
    PATIENT_KEY      NUMBER,
    APPOINTMENT_KEY  NUMBER,
    BILL_DATE        DATE,
    TOTAL_AMOUNT     NUMBER(12,2),
    PAID_AMOUNT      NUMBER(12,2),
    PAYMENT_STATUS   STRING,
    IS_VALID_RECORD  BOOLEAN,
    CREATED_BY       STRING DEFAULT CURRENT_USER(),
    CREATED_ON       TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

USE SCHEMA CURATED;

-- Clear existing data
TRUNCATE TABLE DIM_PATIENT;

-- MERGE for DIM_PATIENT with SCD Type 2
MERGE INTO DIM_PATIENT AS tgt
USING (
    SELECT 
        PATIENT_ID,
        NAME,
        DOB,
        GENDER,
        EMAIL,
        PHONE,
        CITY,
        STATE,
        CURRENT_DATE() AS LOAD_DATE,
        ROW_NUMBER() OVER (PARTITION BY PATIENT_ID ORDER BY CREATED_ON DESC) AS RN
    FROM VALIDATED.VALIDATED_PATIENTS
    WHERE IS_VALID_RECORD = TRUE
    QUALIFY RN = 1
) AS src
ON tgt.PATIENT_ID = src.PATIENT_ID AND tgt.IS_CURRENT = 'Y'

-- When matched and data changed, close the old record
WHEN MATCHED AND (
    tgt.NAME != src.NAME OR
    tgt.CITY != src.CITY OR
    tgt.STATE != src.STATE OR
    tgt.PHONE != src.PHONE OR
    tgt.EMAIL != src.EMAIL
) THEN UPDATE SET
    tgt.IS_CURRENT = 'N',
    tgt.VALID_TO = src.LOAD_DATE

-- Insert new record (for new patients or changed records)
WHEN NOT MATCHED THEN INSERT (
    PATIENT_ID, NAME, DOB, GENDER, EMAIL, PHONE, CITY, STATE,
    VALID_FROM, VALID_TO, IS_CURRENT, VERSION_NUMBER,
    CREATED_BY, CREATED_ON, SOURCE_TABLE
) VALUES (
    src.PATIENT_ID, src.NAME, src.DOB, src.GENDER, src.EMAIL, src.PHONE,
    src.CITY, src.STATE,
    src.LOAD_DATE, TO_DATE('9999-12-31'), 'Y',
    COALESCE((SELECT MAX(VERSION_NUMBER) + 1 FROM DIM_PATIENT WHERE PATIENT_ID = src.PATIENT_ID), 1),
    CURRENT_USER(), CURRENT_TIMESTAMP(), 'VALIDATED_PATIENTS'
);


USE SCHEMA CURATED;

-- Clear existing data
TRUNCATE TABLE DIM_DOCTOR;

-- MERGE for DIM_DOCTOR with SCD Type 2
MERGE INTO DIM_DOCTOR AS tgt
USING (
    SELECT DISTINCT
        DOCTOR_ID,
        DOCTOR_NAME,
        SPECIALIZATION,
        DEPARTMENT,
        CURRENT_DATE() AS LOAD_DATE
    FROM (
        SELECT 
            DOCTOR AS DOCTOR_ID,
            DOCTOR AS DOCTOR_NAME,
            DEPARTMENT AS SPECIALIZATION,
            DEPARTMENT,
            ROW_NUMBER() OVER (PARTITION BY DOCTOR ORDER BY CREATED_ON DESC) AS RN
        FROM VALIDATED.VALIDATED_APPOINTMENTS
        WHERE IS_VALID_RECORD = TRUE
    )
    WHERE RN = 1
) AS src
ON tgt.DOCTOR_ID = src.DOCTOR_ID AND tgt.IS_CURRENT = 'Y'

-- When matched and data changed, close the old record
WHEN MATCHED AND (
    tgt.DOCTOR_NAME != src.DOCTOR_NAME OR
    tgt.SPECIALIZATION != src.SPECIALIZATION OR
    tgt.DEPARTMENT != src.DEPARTMENT
) THEN UPDATE SET
    tgt.IS_CURRENT = 'N',
    tgt.VALID_TO = src.LOAD_DATE

-- Insert new record
WHEN NOT MATCHED THEN INSERT (
    DOCTOR_ID, DOCTOR_NAME, SPECIALIZATION, DEPARTMENT,
    VALID_FROM, VALID_TO, IS_CURRENT, VERSION_NUMBER,
    CREATED_BY, CREATED_ON, SOURCE_TABLE
) VALUES (
    src.DOCTOR_ID, src.DOCTOR_NAME, src.SPECIALIZATION, src.DEPARTMENT,
    src.LOAD_DATE, TO_DATE('9999-12-31'), 'Y',
    COALESCE((SELECT MAX(VERSION_NUMBER) + 1 FROM DIM_DOCTOR WHERE DOCTOR_ID = src.DOCTOR_ID), 1),
    CURRENT_USER(), CURRENT_TIMESTAMP(), 'VALIDATED_APPOINTMENTS'
);
USE SCHEMA CURATED;

-- Clear existing data
TRUNCATE TABLE DIM_DEPARTMENT;

-- MERGE for DIM_DEPARTMENT (Only from APPOINTMENTS)
MERGE INTO DIM_DEPARTMENT AS tgt
USING (
    SELECT DISTINCT
        UPPER(SUBSTR(DEPARTMENT, 1, 4)) AS DEPT_CODE,
        INITCAP(TRIM(DEPARTMENT)) AS DEPT_NAME
    FROM VALIDATED.VALIDATED_APPOINTMENTS
    WHERE DEPARTMENT IS NOT NULL 
      AND DEPARTMENT != ''
      AND IS_VALID_RECORD = TRUE
) AS src
ON tgt.DEPT_CODE = src.DEPT_CODE

WHEN MATCHED THEN UPDATE SET
    tgt.DEPT_NAME = src.DEPT_NAME,
    tgt.CREATED_BY = CURRENT_USER(),
    tgt.CREATED_ON = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN INSERT (
    DEPT_CODE, DEPT_NAME, CREATED_BY, CREATED_ON
) VALUES (
    src.DEPT_CODE, src.DEPT_NAME, CURRENT_USER(), CURRENT_TIMESTAMP()
);



USE SCHEMA CURATED;

-- Clear existing data
TRUNCATE TABLE FACT_APPOINTMENTS;

-- MERGE for FACT_APPOINTMENTS
MERGE INTO FACT_APPOINTMENTS AS tgt
USING (
    SELECT 
        vAPPT.APPOINTMENT_ID,
        vAPPT.PATIENT_ID,
        vAPPT.DOCTOR AS DOCTOR_ID,
        vAPPT.DEPARTMENT,
        vAPPT.APPOINTMENT_DATE,
        vAPPT.STATUS,
        vAPPT.IS_VALID_RECORD,
        
        -- Get surrogate keys from dimension tables
        dp.PATIENT_KEY,
        dd.DOCTOR_KEY,
        ddept.DEPT_KEY,
        NULL AS DATE_KEY  -- Will add later when DIM_DATE is loaded
        
    FROM VALIDATED.VALIDATED_APPOINTMENTS vAPPT
    LEFT JOIN CURATED.DIM_PATIENT dp 
        ON vAPPT.PATIENT_ID = dp.PATIENT_ID AND dp.IS_CURRENT = 'Y'
    LEFT JOIN CURATED.DIM_DOCTOR dd 
        ON vAPPT.DOCTOR = dd.DOCTOR_ID AND dd.IS_CURRENT = 'Y'
    LEFT JOIN CURATED.DIM_DEPARTMENT ddept 
        ON UPPER(SUBSTR(vAPPT.DEPARTMENT, 1, 4)) = ddept.DEPT_CODE
    WHERE vAPPT.IS_VALID_RECORD = TRUE
    
) AS src
ON tgt.APPOINTMENT_ID = src.APPOINTMENT_ID

WHEN MATCHED THEN UPDATE SET
    tgt.PATIENT_KEY = src.PATIENT_KEY,
    tgt.DOCTOR_KEY = src.DOCTOR_KEY,
    tgt.DEPT_KEY = src.DEPT_KEY,
    tgt.DATE_KEY = src.DATE_KEY,
    tgt.APPOINTMENT_DATE = src.APPOINTMENT_DATE,
    tgt.STATUS = src.STATUS,
    tgt.IS_VALID_RECORD = src.IS_VALID_RECORD,
    tgt.CREATED_BY = CURRENT_USER(),
    tgt.CREATED_ON = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN INSERT (
    APPOINTMENT_ID,
    PATIENT_KEY,
    DOCTOR_KEY,
    DEPT_KEY,
    DATE_KEY,
    APPOINTMENT_DATE,
    STATUS,
    IS_VALID_RECORD,
    CREATED_BY,
    CREATED_ON
) VALUES (
    src.APPOINTMENT_ID,
    src.PATIENT_KEY,
    src.DOCTOR_KEY,
    src.DEPT_KEY,
    src.DATE_KEY,
    src.APPOINTMENT_DATE,
    src.STATUS,
    src.IS_VALID_RECORD,
    CURRENT_USER(),
    CURRENT_TIMESTAMP()
);

USE SCHEMA CURATED;

-- Clear existing data
TRUNCATE TABLE FACT_MEDICAL_RECORDS;

-- MERGE for FACT_MEDICAL_RECORDS
MERGE INTO FACT_MEDICAL_RECORDS AS tgt
USING (
    SELECT 
        vREC.RECORD_ID,
        vREC.PATIENT_ID,
        vREC.RECORD_DATE,
        vREC.DIAGNOSIS,
        vREC.PROCEDURE AS PROCEDURE_NAME,
        vREC.IS_VALID_RECORD,
        
        -- Get surrogate keys from dimension tables
        dp.PATIENT_KEY
        
    FROM VALIDATED.VALIDATED_MEDICAL_RECORDS vREC
    LEFT JOIN CURATED.DIM_PATIENT dp 
        ON vREC.PATIENT_ID = dp.PATIENT_ID AND dp.IS_CURRENT = 'Y'
    WHERE vREC.IS_VALID_RECORD = TRUE
    
) AS src
ON tgt.RECORD_ID = src.RECORD_ID

WHEN MATCHED THEN UPDATE SET
    tgt.PATIENT_KEY = src.PATIENT_KEY,
    tgt.RECORD_DATE = src.RECORD_DATE,
    tgt.DIAGNOSIS = src.DIAGNOSIS,
    tgt.PROCEDURE_NAME = src.PROCEDURE_NAME,
    tgt.IS_VALID_RECORD = src.IS_VALID_RECORD,
    tgt.CREATED_BY = CURRENT_USER(),
    tgt.CREATED_ON = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN INSERT (
    RECORD_ID,
    PATIENT_KEY,
    RECORD_DATE,
    DIAGNOSIS,
    PROCEDURE_NAME,
    IS_VALID_RECORD,
    CREATED_BY,
    CREATED_ON
) VALUES (
    src.RECORD_ID,
    src.PATIENT_KEY,
    src.RECORD_DATE,
    src.DIAGNOSIS,
    src.PROCEDURE_NAME,
    src.IS_VALID_RECORD,
    CURRENT_USER(),
    CURRENT_TIMESTAMP()
);



USE SCHEMA CURATED;

-- Clear existing data
TRUNCATE TABLE FACT_BILLING;

-- MERGE for FACT_BILLING
MERGE INTO FACT_BILLING AS tgt
USING (
    SELECT 
        vBILL.BILL_ID,
        vBILL.PATIENT_ID,
        vBILL.APPOINTMENT_ID,
        vBILL.BILL_DATE,
        vBILL.TOTAL_AMOUNT,
        vBILL.PAID_AMOUNT,
        vBILL.PAYMENT_STATUS,
        vBILL.IS_VALID_RECORD,
        
        -- Get surrogate keys from dimension tables
        dp.PATIENT_KEY,
        fa.APPOINTMENT_KEY
        
    FROM VALIDATED.VALIDATED_BILLING vBILL
    LEFT JOIN CURATED.DIM_PATIENT dp 
        ON vBILL.PATIENT_ID = dp.PATIENT_ID AND dp.IS_CURRENT = 'Y'
    LEFT JOIN CURATED.FACT_APPOINTMENTS fa 
        ON vBILL.APPOINTMENT_ID = fa.APPOINTMENT_ID
    WHERE vBILL.IS_VALID_RECORD = TRUE
    
) AS src
ON tgt.BILL_ID = src.BILL_ID

WHEN MATCHED THEN UPDATE SET
    tgt.PATIENT_KEY = src.PATIENT_KEY,
    tgt.APPOINTMENT_KEY = src.APPOINTMENT_KEY,
    tgt.BILL_DATE = src.BILL_DATE,
    tgt.TOTAL_AMOUNT = src.TOTAL_AMOUNT,
    tgt.PAID_AMOUNT = src.PAID_AMOUNT,
    tgt.PAYMENT_STATUS = src.PAYMENT_STATUS,
    tgt.IS_VALID_RECORD = src.IS_VALID_RECORD,
    tgt.CREATED_BY = CURRENT_USER(),
    tgt.CREATED_ON = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN INSERT (
    BILL_ID,
    PATIENT_KEY,
    APPOINTMENT_KEY,
    BILL_DATE,
    TOTAL_AMOUNT,
    PAID_AMOUNT,
    PAYMENT_STATUS,
    IS_VALID_RECORD,
    CREATED_BY,
    CREATED_ON
) VALUES (
    src.BILL_ID,
    src.PATIENT_KEY,
    src.APPOINTMENT_KEY,
    src.BILL_DATE,
    src.TOTAL_AMOUNT,
    src.PAID_AMOUNT,
    src.PAYMENT_STATUS,
    src.IS_VALID_RECORD,
    CURRENT_USER(),
    CURRENT_TIMESTAMP()
);

SELECT 'DIM_PATIENT' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM DIM_PATIENT
UNION ALL
SELECT 'DIM_DOCTOR', COUNT(*) FROM DIM_DOCTOR
UNION ALL
SELECT 'DIM_DEPARTMENT', COUNT(*) FROM DIM_DEPARTMENT
UNION ALL
SELECT 'FACT_APPOINTMENTS', COUNT(*) FROM FACT_APPOINTMENTS
UNION ALL
SELECT 'FACT_MEDICAL_RECORDS', COUNT(*) FROM FACT_MEDICAL_RECORDS
UNION ALL
SELECT 'FACT_BILLING', COUNT(*) FROM FACT_BILLING;

