-- 1. Create Warehouse (Compute)
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
WITH WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

-- 2. Use Warehouse
USE WAREHOUSE COMPUTE_WH;

-- 3. Then create Database
CREATE DATABASE IF NOT EXISTS SNOW_VALUT;

-- 4. Use Database
USE DATABASE SNOW_VALUT;

-- =========================================================
-- SNOW_VALUT COMPLETE SETUP (FULL ACCESS FOR ALL)
-- =========================================================


USE ROLE ACCOUNTADMIN;

-- =========================================================
-- DATABASE
-- =========================================================

CREATE DATABASE IF NOT EXISTS SNOW_VALUT;
USE DATABASE SNOW_VALUT;


-- =========================================================
-- SCHEMAS
-- =========================================================

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS VALIDATED;
CREATE SCHEMA IF NOT EXISTS CURATED;
CREATE SCHEMA IF NOT EXISTS GOVERNANCE;
CREATE SCHEMA IF NOT EXISTS UTIL;
CREATE SCHEMA IF NOT EXISTS ANALYTICAL;
CREATE SCHEMA IF NOT EXISTS CONTROL;
CREATE SCHEMA IF NOT EXISTS TASKS;


use schema raw;


-- 1. Create File Format
CREATE OR REPLACE FILE FORMAT MY_CSV_FORMAT
TYPE = CSV
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"';


-- 2. Create Internal Stage
CREATE OR REPLACE STAGE INTERNAL_STAGE;

LIST @INTERNAL_STAGE;


USE DATABASE SNOW_VALUT;
USE SCHEMA RAW;

//create raw tables

CREATE OR REPLACE TABLE RAW_APPOINTMENTS (
    APPOINTMENT_ID STRING,
    PATIENT_ID STRING,
    DOCTOR STRING,
    DEPARTMENT STRING,
    APPOINTMENT_DATE STRING,
    STATUS STRING,

    -- ✅ Audit Columns
    CREATED_BY STRING DEFAULT CURRENT_USER(),
    CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    IS_ACTIVE BOOLEAN DEFAULT TRUE
);


CREATE OR REPLACE TABLE RAW.RAW_BILLING (
    BILL_ID STRING,
    PATIENT_ID STRING,
    APPOINTMENT_ID STRING,
    BILL_DATE STRING,
    TOTAL_AMOUNT STRING,
    PAID_AMOUNT STRING,
    PAYMENT_STATUS STRING,

    -- ✅ Audit Columns
    CREATED_BY STRING DEFAULT CURRENT_USER(),
    CREATED_ON STRING DEFAULT TO_VARCHAR(CURRENT_TIMESTAMP()),
    IS_ACTIVE STRING DEFAULT 'TRUE'
);

CREATE OR REPLACE TABLE RAW.RAW_MEDICAL_RECORDS (
    RECORD_ID STRING,
    PATIENT_ID STRING,
    RECORD_DATE STRING,
    DIAGNOSIS STRING,
    PROCEDURE STRING,

    -- ✅ Audit Columns
    CREATED_BY STRING DEFAULT CURRENT_USER(),
    CREATED_ON STRING DEFAULT TO_VARCHAR(CURRENT_TIMESTAMP()),
    IS_ACTIVE STRING DEFAULT 'TRUE'
);

CREATE OR REPLACE TABLE RAW.RAW_PATIENTS (
    PATIENT_ID STRING,
    NAME STRING,
    DOB STRING,
    GENDER STRING,
    EMAIL STRING,
    PHONE STRING,
    CITY STRING,
    STATE STRING,

    -- ✅ Audit Columns
    CREATED_BY STRING DEFAULT CURRENT_USER(),
    CREATED_ON STRING DEFAULT TO_VARCHAR(CURRENT_TIMESTAMP()),
    IS_ACTIVE STRING DEFAULT 'TRUE'
);

//copy data from stage to layer
COPY INTO RAW.RAW_PATIENTS
(PATIENT_ID, NAME, DOB, GENDER, EMAIL, PHONE, CITY, STATE)
FROM (
    SELECT $1,$2,$3,$4,$5,$6,$7,$8
    FROM @INTERNAL_STAGE/patients.csv
)
FILE_FORMAT = (FORMAT_NAME = MY_CSV_FORMAT)
ON_ERROR = 'CONTINUE';



COPY INTO RAW.RAW_APPOINTMENTS
(APPOINTMENT_ID, PATIENT_ID, DOCTOR, DEPARTMENT, APPOINTMENT_DATE, STATUS)
FROM (
    SELECT $1,$2,$3,$4,$5,$6
    FROM @INTERNAL_STAGE/appointments.csv
)
FILE_FORMAT = (FORMAT_NAME = MY_CSV_FORMAT)
ON_ERROR = 'CONTINUE';



COPY INTO RAW.RAW_MEDICAL_RECORDS
(RECORD_ID, PATIENT_ID, RECORD_DATE, DIAGNOSIS, PROCEDURE)
FROM (
    SELECT $1,$2,$3,$4,$5
    FROM @INTERNAL_STAGE/medical_records.csv
)
FILE_FORMAT = (FORMAT_NAME = MY_CSV_FORMAT)
ON_ERROR = 'CONTINUE';



COPY INTO RAW.RAW_BILLING
(BILL_ID, PATIENT_ID, APPOINTMENT_ID, BILL_DATE, TOTAL_AMOUNT, PAID_AMOUNT, PAYMENT_STATUS)
FROM (
    SELECT $1,$2,$3,$4,$5,$6,$7
    FROM @INTERNAL_STAGE/billing.csv
)
FILE_FORMAT = (FORMAT_NAME = MY_CSV_FORMAT)
ON_ERROR = 'CONTINUE';














