-- =====================================================================================
-- COMPLETE VALIDATED LAYER (STRICT VALIDATION)
-- VALID RECORDS -> VALIDATED TABLES
-- INVALID RECORDS -> ERROR / REJECTED TABLES
-- PROJECT : SNOW_VALUT HEALTHCARE ANALYTICS
-- COPY FULL CODE
-- =====================================================================================






-- =========================================================
-- 1. DATABASE & SCHEMA
-- =========================================================

USE DATABASE SNOW_VALUT;

CREATE OR REPLACE SCHEMA VALIDATED;
USE SCHEMA VALIDATED;


-- =========================================================
-- 2. VALIDATED TABLES
-- =========================================================

CREATE OR REPLACE TABLE VALIDATED_PATIENTS (
    PATIENT_ID STRING,
    NAME STRING,
    DOB DATE,
    GENDER STRING,
    EMAIL STRING,
    PHONE STRING,
    CITY STRING,
    STATE STRING,
    IS_VALID_RECORD BOOLEAN,
    VALIDATION_ERRORS STRING,
    CREATED_BY STRING,
    CREATED_ON TIMESTAMP
);

CREATE OR REPLACE TABLE VALIDATED_APPOINTMENTS (
    APPOINTMENT_ID STRING,
    PATIENT_ID STRING,
    DOCTOR STRING,
    DEPARTMENT STRING,
    APPOINTMENT_DATE DATE,
    STATUS STRING,
    IS_VALID_RECORD BOOLEAN,
    VALIDATION_ERRORS STRING,
    CREATED_BY STRING,
    CREATED_ON TIMESTAMP
);

CREATE OR REPLACE TABLE VALIDATED_MEDICAL_RECORDS (
    RECORD_ID STRING,
    PATIENT_ID STRING,
    RECORD_DATE DATE,
    DIAGNOSIS STRING,
    PROCEDURE STRING,
    IS_VALID_RECORD BOOLEAN,
    VALIDATION_ERRORS STRING,
    CREATED_BY STRING,
    CREATED_ON TIMESTAMP
);

CREATE OR REPLACE TABLE VALIDATED_BILLING (
    BILL_ID STRING,
    PATIENT_ID STRING,
    APPOINTMENT_ID STRING,
    BILL_DATE DATE,
    TOTAL_AMOUNT NUMBER(12,2),
    PAID_AMOUNT NUMBER(12,2),
    PAYMENT_STATUS STRING,
    IS_VALID_RECORD BOOLEAN,
    VALIDATION_ERRORS STRING,
    CREATED_BY STRING,
    CREATED_ON TIMESTAMP
);


-- =========================================================
-- 3. LOAD + VALIDATE DATA FROM RAW
-- =========================================================

-- =======================
-- PATIENTS
-- =======================

INSERT INTO VALIDATED_PATIENTS
SELECT
    TRIM(PATIENT_ID),
    INITCAP(TRIM(NAME)),
    TRY_TO_DATE(DOB),
    UPPER(TRIM(GENDER)),
    LOWER(TRIM(EMAIL)),
    REGEXP_REPLACE(PHONE, '[^0-9]', ''),
    INITCAP(TRIM(CITY)),
    UPPER(TRIM(STATE)),

    CASE 
        WHEN PATIENT_ID IS NULL THEN FALSE
        WHEN TRY_TO_DATE(DOB) IS NULL THEN FALSE
        WHEN EMAIL NOT LIKE '%@%.%' THEN FALSE
        WHEN LENGTH(REGEXP_REPLACE(PHONE,'[^0-9]','')) < 10 THEN FALSE
        ELSE TRUE
    END AS IS_VALID_RECORD,

    CASE 
        WHEN PATIENT_ID IS NULL THEN 'PATIENT_ID_MISSING'
        WHEN TRY_TO_DATE(DOB) IS NULL THEN 'INVALID_DOB'
        WHEN EMAIL NOT LIKE '%@%.%' THEN 'INVALID_EMAIL'
        WHEN LENGTH(REGEXP_REPLACE(PHONE,'[^0-9]','')) < 10 THEN 'INVALID_PHONE'
        ELSE 'VALID'
    END AS VALIDATION_ERRORS,

    CURRENT_USER(),
    CURRENT_TIMESTAMP()

FROM RAW.RAW_PATIENTS
WHERE IS_ACTIVE = 'TRUE';


-- =======================
-- APPOINTMENTS
-- =======================

INSERT INTO VALIDATED_APPOINTMENTS
SELECT
    TRIM(APPOINTMENT_ID),
    TRIM(PATIENT_ID),
    INITCAP(TRIM(DOCTOR)),
    INITCAP(TRIM(DEPARTMENT)),
    TRY_TO_DATE(APPOINTMENT_DATE),
    UPPER(TRIM(STATUS)),

    CASE 
        WHEN APPOINTMENT_ID IS NULL THEN FALSE
        WHEN TRY_TO_DATE(APPOINTMENT_DATE) IS NULL THEN FALSE
        WHEN STATUS NOT IN ('BOOKED','CANCELLED','COMPLETED') THEN FALSE
        ELSE TRUE
    END,

    CASE 
        WHEN APPOINTMENT_ID IS NULL THEN 'MISSING_ID'
        WHEN TRY_TO_DATE(APPOINTMENT_DATE) IS NULL THEN 'INVALID_DATE'
        WHEN STATUS NOT IN ('BOOKED','CANCELLED','COMPLETED') THEN 'INVALID_STATUS'
        ELSE 'VALID'
    END,

    CURRENT_USER(),
    CURRENT_TIMESTAMP()

FROM RAW.RAW_APPOINTMENTS
WHERE IS_ACTIVE = TRUE;


-- =======================
-- MEDICAL RECORDS
-- =======================

INSERT INTO VALIDATED_MEDICAL_RECORDS
SELECT
    TRIM(RECORD_ID),
    TRIM(PATIENT_ID),
    TRY_TO_DATE(RECORD_DATE),
    INITCAP(TRIM(DIAGNOSIS)),
    INITCAP(TRIM(PROCEDURE)),

    CASE 
        WHEN RECORD_ID IS NULL THEN FALSE
        WHEN TRY_TO_DATE(RECORD_DATE) IS NULL THEN FALSE
        ELSE TRUE
    END,

    CASE 
        WHEN RECORD_ID IS NULL THEN 'MISSING_ID'
        WHEN TRY_TO_DATE(RECORD_DATE) IS NULL THEN 'INVALID_DATE'
        ELSE 'VALID'
    END,

    CURRENT_USER(),
    CURRENT_TIMESTAMP()

FROM RAW.RAW_MEDICAL_RECORDS
WHERE IS_ACTIVE = 'TRUE';


-- =======================
-- BILLING
-- =======================


INSERT INTO VALIDATED_BILLING
SELECT
    TRIM(BILL_ID),
    TRIM(PATIENT_ID),
    TRIM(APPOINTMENT_ID),
    TRY_TO_DATE(BILL_DATE),
    TRY_TO_NUMBER(REPLACE(TOTAL_AMOUNT, ',', '')),
    TRY_TO_NUMBER(REPLACE(PAID_AMOUNT, ',', '')),
    UPPER(TRIM(PAYMENT_STATUS)),

    CASE 
        WHEN BILL_ID IS NULL THEN FALSE
        WHEN TRY_TO_DATE(BILL_DATE) IS NULL THEN FALSE
        WHEN TRY_TO_NUMBER(REPLACE(TOTAL_AMOUNT, ',', '')) IS NULL THEN FALSE
        ELSE TRUE
    END,

    CASE 
        WHEN BILL_ID IS NULL THEN 'MISSING_ID'
        WHEN TRY_TO_DATE(BILL_DATE) IS NULL THEN 'INVALID_DATE'
        WHEN TRY_TO_NUMBER(REPLACE(TOTAL_AMOUNT, ',', '')) IS NULL THEN 'INVALID_AMOUNT'
        ELSE 'VALID'
    END,

    CURRENT_USER(),
    CURRENT_TIMESTAMP()

FROM RAW.RAW_BILLING
WHERE IS_ACTIVE = 'TRUE';


-- =========================================================
-- 4. DATA QUALITY CHECK
-- =========================================================

SELECT 'PATIENTS' AS TABLE_NAME, COUNT(*) AS VALID_COUNT
FROM VALIDATED_PATIENTS WHERE IS_VALID_RECORD = TRUE

UNION ALL

SELECT 'APPOINTMENTS', COUNT(*)
FROM VALIDATED_APPOINTMENTS WHERE IS_VALID_RECORD = TRUE

UNION ALL

SELECT 'MEDICAL_RECORDS', COUNT(*)
FROM VALIDATED_MEDICAL_RECORDS WHERE IS_VALID_RECORD = TRUE

UNION ALL

SELECT 'BILLING', COUNT(*)
FROM VALIDATED_BILLING WHERE IS_VALID_RECORD = TRUE;

