-- 1. Create Warehouse (Compute)
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
WITH WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

-- 2. Use Warehouse
USE WAREHOUSE COMPUTE_WH;

-- 3. Then create Database
CREATE DATABASE IF NOT EXISTS SNOW_VALUT;

-- 4. Use Database
USE DATABASE SNOW_VALUT;

-- =========================================================
-- SNOW_VALUT COMPLETE SETUP (FULL ACCESS FOR ALL)
-- =========================================================


USE ROLE ACCOUNTADMIN;

-- =========================================================
-- DATABASE
-- =========================================================

CREATE DATABASE IF NOT EXISTS SNOW_VALUT;
USE DATABASE SNOW_VALUT;


-- =========================================================
-- SCHEMAS
-- =========================================================

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS VALIDATED;
CREATE SCHEMA IF NOT EXISTS CURATED;
CREATE SCHEMA IF NOT EXISTS GOVERNANCE;
CREATE SCHEMA IF NOT EXISTS UTIL;
CREATE SCHEMA IF NOT EXISTS ANALYTICAL;
CREATE SCHEMA IF NOT EXISTS CONTROL;
CREATE SCHEMA IF NOT EXISTS TASKS;


use schema raw;


-- 1. Create File Format
CREATE OR REPLACE FILE FORMAT MY_CSV_FORMAT
TYPE = CSV
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"';


-- 2. Create Internal Stage
CREATE OR REPLACE STAGE INTERNAL_STAGE;

LIST @INTERNAL_STAGE;


USE DATABASE SNOW_VALUT;
USE SCHEMA RAW;

//create raw tables

CREATE OR REPLACE TABLE RAW_APPOINTMENTS (
    APPOINTMENT_ID STRING,
    PATIENT_ID STRING,
    DOCTOR STRING,
    DEPARTMENT STRING,
    APPOINTMENT_DATE STRING,
    STATUS STRING,

    -- ✅ Audit Columns
    CREATED_BY STRING DEFAULT CURRENT_USER(),
    CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    IS_ACTIVE BOOLEAN DEFAULT TRUE
);


CREATE OR REPLACE TABLE RAW.RAW_BILLING (
    BILL_ID STRING,
    PATIENT_ID STRING,
    APPOINTMENT_ID STRING,
    BILL_DATE STRING,
    TOTAL_AMOUNT STRING,
    PAID_AMOUNT STRING,
    PAYMENT_STATUS STRING,

    -- ✅ Audit Columns
    CREATED_BY STRING DEFAULT CURRENT_USER(),
    CREATED_ON STRING DEFAULT TO_VARCHAR(CURRENT_TIMESTAMP()),
    IS_ACTIVE STRING DEFAULT 'TRUE'
);

CREATE OR REPLACE TABLE RAW.RAW_MEDICAL_RECORDS (
    RECORD_ID STRING,
    PATIENT_ID STRING,
    RECORD_DATE STRING,
    DIAGNOSIS STRING,
    PROCEDURE STRING,

    -- ✅ Audit Columns
    CREATED_BY STRING DEFAULT CURRENT_USER(),
    CREATED_ON STRING DEFAULT TO_VARCHAR(CURRENT_TIMESTAMP()),
    IS_ACTIVE STRING DEFAULT 'TRUE'
);

CREATE OR REPLACE TABLE RAW.RAW_PATIENTS (
    PATIENT_ID STRING,
    NAME STRING,
    DOB STRING,
    GENDER STRING,
    EMAIL STRING,
    PHONE STRING,
    CITY STRING,
    STATE STRING,

    -- ✅ Audit Columns
    CREATED_BY STRING DEFAULT CURRENT_USER(),
    CREATED_ON STRING DEFAULT TO_VARCHAR(CURRENT_TIMESTAMP()),
    IS_ACTIVE STRING DEFAULT 'TRUE'
);

//copy data from stage to layer
COPY INTO RAW.RAW_PATIENTS
(PATIENT_ID, NAME, DOB, GENDER, EMAIL, PHONE, CITY, STATE)
FROM (
    SELECT $1,$2,$3,$4,$5,$6,$7,$8
    FROM @INTERNAL_STAGE/patients.csv
)
FILE_FORMAT = (FORMAT_NAME = MY_CSV_FORMAT)
ON_ERROR = 'CONTINUE';



COPY INTO RAW.RAW_APPOINTMENTS
(APPOINTMENT_ID, PATIENT_ID, DOCTOR, DEPARTMENT, APPOINTMENT_DATE, STATUS)
FROM (
    SELECT $1,$2,$3,$4,$5,$6
    FROM @INTERNAL_STAGE/appointments.csv
)
FILE_FORMAT = (FORMAT_NAME = MY_CSV_FORMAT)
ON_ERROR = 'CONTINUE';



COPY INTO RAW.RAW_MEDICAL_RECORDS
(RECORD_ID, PATIENT_ID, RECORD_DATE, DIAGNOSIS, PROCEDURE)
FROM (
    SELECT $1,$2,$3,$4,$5
    FROM @INTERNAL_STAGE/medical_records.csv
)
FILE_FORMAT = (FORMAT_NAME = MY_CSV_FORMAT)
ON_ERROR = 'CONTINUE';



COPY INTO RAW.RAW_BILLING
(BILL_ID, PATIENT_ID, APPOINTMENT_ID, BILL_DATE, TOTAL_AMOUNT, PAID_AMOUNT, PAYMENT_STATUS)
FROM (
    SELECT $1,$2,$3,$4,$5,$6,$7
    FROM @INTERNAL_STAGE/billing.csv
)
FILE_FORMAT = (FORMAT_NAME = MY_CSV_FORMAT)
ON_ERROR = 'CONTINUE';


-- =====================================================================================
-- COMPLETE VALIDATED LAYER (STRICT VALIDATION)
-- VALID RECORDS -> VALIDATED TABLES
-- INVALID RECORDS -> ERROR / REJECTED TABLES
-- PROJECT : SNOW_VALUT HEALTHCARE ANALYTICS
-- COPY FULL CODE
-- =====================================================================================






-- =========================================================
-- 1. DATABASE & SCHEMA
-- =========================================================

USE DATABASE SNOW_VALUT;

CREATE OR REPLACE SCHEMA VALIDATED;
USE SCHEMA VALIDATED;


-- =========================================================
-- 2. VALIDATED TABLES
-- =========================================================

CREATE OR REPLACE TABLE VALIDATED_PATIENTS (
    PATIENT_ID STRING,
    NAME STRING,
    DOB DATE,
    GENDER STRING,
    EMAIL STRING,
    PHONE STRING,
    CITY STRING,
    STATE STRING,
    IS_VALID_RECORD BOOLEAN,
    VALIDATION_ERRORS STRING,
    CREATED_BY STRING,
    CREATED_ON TIMESTAMP
);

CREATE OR REPLACE TABLE VALIDATED_APPOINTMENTS (
    APPOINTMENT_ID STRING,
    PATIENT_ID STRING,
    DOCTOR STRING,
    DEPARTMENT STRING,
    APPOINTMENT_DATE DATE,
    STATUS STRING,
    IS_VALID_RECORD BOOLEAN,
    VALIDATION_ERRORS STRING,
    CREATED_BY STRING,
    CREATED_ON TIMESTAMP
);

CREATE OR REPLACE TABLE VALIDATED_MEDICAL_RECORDS (
    RECORD_ID STRING,
    PATIENT_ID STRING,
    RECORD_DATE DATE,
    DIAGNOSIS STRING,
    PROCEDURE STRING,
    IS_VALID_RECORD BOOLEAN,
    VALIDATION_ERRORS STRING,
    CREATED_BY STRING,
    CREATED_ON TIMESTAMP
);

CREATE OR REPLACE TABLE VALIDATED_BILLING (
    BILL_ID STRING,
    PATIENT_ID STRING,
    APPOINTMENT_ID STRING,
    BILL_DATE DATE,
    TOTAL_AMOUNT NUMBER(12,2),
    PAID_AMOUNT NUMBER(12,2),
    PAYMENT_STATUS STRING,
    IS_VALID_RECORD BOOLEAN,
    VALIDATION_ERRORS STRING,
    CREATED_BY STRING,
    CREATED_ON TIMESTAMP
);


-- =========================================================
-- 3. LOAD + VALIDATE DATA FROM RAW
-- =========================================================

-- =======================
-- PATIENTS
-- =======================

INSERT INTO VALIDATED_PATIENTS
SELECT
    TRIM(PATIENT_ID),
    INITCAP(TRIM(NAME)),
    TRY_TO_DATE(DOB),
    UPPER(TRIM(GENDER)),
    LOWER(TRIM(EMAIL)),
    REGEXP_REPLACE(PHONE, '[^0-9]', ''),
    INITCAP(TRIM(CITY)),
    UPPER(TRIM(STATE)),

    CASE 
        WHEN PATIENT_ID IS NULL THEN FALSE
        WHEN TRY_TO_DATE(DOB) IS NULL THEN FALSE
        WHEN EMAIL NOT LIKE '%@%.%' THEN FALSE
        WHEN LENGTH(REGEXP_REPLACE(PHONE,'[^0-9]','')) < 10 THEN FALSE
        ELSE TRUE
    END AS IS_VALID_RECORD,

    CASE 
        WHEN PATIENT_ID IS NULL THEN 'PATIENT_ID_MISSING'
        WHEN TRY_TO_DATE(DOB) IS NULL THEN 'INVALID_DOB'
        WHEN EMAIL NOT LIKE '%@%.%' THEN 'INVALID_EMAIL'
        WHEN LENGTH(REGEXP_REPLACE(PHONE,'[^0-9]','')) < 10 THEN 'INVALID_PHONE'
        ELSE 'VALID'
    END AS VALIDATION_ERRORS,

    CURRENT_USER(),
    CURRENT_TIMESTAMP()

FROM RAW.RAW_PATIENTS
WHERE IS_ACTIVE = 'TRUE';


-- =======================
-- APPOINTMENTS
-- =======================

INSERT INTO VALIDATED_APPOINTMENTS
SELECT
    TRIM(APPOINTMENT_ID),
    TRIM(PATIENT_ID),
    INITCAP(TRIM(DOCTOR)),
    INITCAP(TRIM(DEPARTMENT)),
    TRY_TO_DATE(APPOINTMENT_DATE),
    UPPER(TRIM(STATUS)),

    CASE 
        WHEN APPOINTMENT_ID IS NULL THEN FALSE
        WHEN TRY_TO_DATE(APPOINTMENT_DATE) IS NULL THEN FALSE
        WHEN STATUS NOT IN ('BOOKED','CANCELLED','COMPLETED') THEN FALSE
        ELSE TRUE
    END,

    CASE 
        WHEN APPOINTMENT_ID IS NULL THEN 'MISSING_ID'
        WHEN TRY_TO_DATE(APPOINTMENT_DATE) IS NULL THEN 'INVALID_DATE'
        WHEN STATUS NOT IN ('BOOKED','CANCELLED','COMPLETED') THEN 'INVALID_STATUS'
        ELSE 'VALID'
    END,

    CURRENT_USER(),
    CURRENT_TIMESTAMP()

FROM RAW.RAW_APPOINTMENTS
WHERE IS_ACTIVE = TRUE;


-- =======================
-- MEDICAL RECORDS
-- =======================

INSERT INTO VALIDATED_MEDICAL_RECORDS
SELECT
    TRIM(RECORD_ID),
    TRIM(PATIENT_ID),
    TRY_TO_DATE(RECORD_DATE),
    INITCAP(TRIM(DIAGNOSIS)),
    INITCAP(TRIM(PROCEDURE)),

    CASE 
        WHEN RECORD_ID IS NULL THEN FALSE
        WHEN TRY_TO_DATE(RECORD_DATE) IS NULL THEN FALSE
        ELSE TRUE
    END,

    CASE 
        WHEN RECORD_ID IS NULL THEN 'MISSING_ID'
        WHEN TRY_TO_DATE(RECORD_DATE) IS NULL THEN 'INVALID_DATE'
        ELSE 'VALID'
    END,

    CURRENT_USER(),
    CURRENT_TIMESTAMP()

FROM RAW.RAW_MEDICAL_RECORDS
WHERE IS_ACTIVE = 'TRUE';


-- =======================
-- BILLING
-- =======================


INSERT INTO VALIDATED_BILLING
SELECT
    TRIM(BILL_ID),
    TRIM(PATIENT_ID),
    TRIM(APPOINTMENT_ID),
    TRY_TO_DATE(BILL_DATE),
    TRY_TO_NUMBER(REPLACE(TOTAL_AMOUNT, ',', '')),
    TRY_TO_NUMBER(REPLACE(PAID_AMOUNT, ',', '')),
    UPPER(TRIM(PAYMENT_STATUS)),

    CASE 
        WHEN BILL_ID IS NULL THEN FALSE
        WHEN TRY_TO_DATE(BILL_DATE) IS NULL THEN FALSE
        WHEN TRY_TO_NUMBER(REPLACE(TOTAL_AMOUNT, ',', '')) IS NULL THEN FALSE
        ELSE TRUE
    END,

    CASE 
        WHEN BILL_ID IS NULL THEN 'MISSING_ID'
        WHEN TRY_TO_DATE(BILL_DATE) IS NULL THEN 'INVALID_DATE'
        WHEN TRY_TO_NUMBER(REPLACE(TOTAL_AMOUNT, ',', '')) IS NULL THEN 'INVALID_AMOUNT'
        ELSE 'VALID'
    END,

    CURRENT_USER(),
    CURRENT_TIMESTAMP()

FROM RAW.RAW_BILLING
WHERE IS_ACTIVE = 'TRUE';


-- =========================================================
-- 4. DATA QUALITY CHECK
-- =========================================================

SELECT 'PATIENTS' AS TABLE_NAME, COUNT(*) AS VALID_COUNT
FROM VALIDATED_PATIENTS WHERE IS_VALID_RECORD = TRUE

UNION ALL

SELECT 'APPOINTMENTS', COUNT(*)
FROM VALIDATED_APPOINTMENTS WHERE IS_VALID_RECORD = TRUE

UNION ALL

SELECT 'MEDICAL_RECORDS', COUNT(*)
FROM VALIDATED_MEDICAL_RECORDS WHERE IS_VALID_RECORD = TRUE

UNION ALL

SELECT 'BILLING', COUNT(*)
FROM VALIDATED_BILLING WHERE IS_VALID_RECORD = TRUE;








-


USE SCHEMA CURATED;

-- =============================================
-- 1. DIM_PATIENT (SCD TYPE 2)
-- =============================================
CREATE OR REPLACE TABLE DIM_PATIENT (
    PATIENT_KEY      NUMBER AUTOINCREMENT,
    PATIENT_ID       STRING NOT NULL,
    NAME             STRING,
    DOB              DATE,
    GENDER           STRING,
    EMAIL            STRING,
    PHONE            STRING,
    CITY             STRING,
    STATE            STRING,
    
    -- SCD Type 2 Columns
    VALID_FROM       DATE DEFAULT CURRENT_DATE(),
    VALID_TO         DATE DEFAULT TO_DATE('9999-12-31', 'YYYY-MM-DD'),
    IS_CURRENT       STRING DEFAULT 'Y',
    VERSION_NUMBER   NUMBER DEFAULT 1,
    
    -- Audit
    CREATED_BY       STRING DEFAULT CURRENT_USER(),
    CREATED_ON       TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_TABLE     STRING
);

-- =============================================
-- 2. DIM_DOCTOR (SCD TYPE 2)
-- =============================================
CREATE OR REPLACE TABLE DIM_DOCTOR (
    DOCTOR_KEY       NUMBER AUTOINCREMENT,
    DOCTOR_ID        STRING NOT NULL,
    DOCTOR_NAME      STRING,
    SPECIALIZATION   STRING,
    DEPARTMENT       STRING,
    
    -- SCD Type 2 Columns
    VALID_FROM       DATE DEFAULT CURRENT_DATE(),
    VALID_TO         DATE DEFAULT TO_DATE('9999-12-31', 'YYYY-MM-DD'),
    IS_CURRENT       STRING DEFAULT 'Y',
    VERSION_NUMBER   NUMBER DEFAULT 1,
    
    -- Audit
    CREATED_BY       STRING DEFAULT CURRENT_USER(),
    CREATED_ON       TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_TABLE     STRING
);

-- =============================================
-- 3. DIM_DATE (Static - No SCD)
-- =============================================
CREATE OR REPLACE TABLE DIM_DATE (
    DATE_KEY         NUMBER PRIMARY KEY,
    FULL_DATE        DATE,
    YEAR_NUM         NUMBER,
    MONTH_NUM        NUMBER,
    MONTH_NAME       STRING,
    DAY_NAME         STRING,
    IS_WEEKEND       STRING
);

-- =============================================
-- 4. DIM_DEPARTMENT (Lookup - No SCD)
-- =============================================
CREATE OR REPLACE TABLE DIM_DEPARTMENT (
    DEPT_KEY         NUMBER AUTOINCREMENT,
    DEPT_CODE        STRING,
    DEPT_NAME        STRING,
    CREATED_BY       STRING DEFAULT CURRENT_USER(),
    CREATED_ON       TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- =============================================
-- 5. FACT_APPOINTMENTS
-- =============================================
CREATE OR REPLACE TABLE FACT_APPOINTMENTS (
    APPOINTMENT_KEY  NUMBER AUTOINCREMENT,
    APPOINTMENT_ID   STRING,
    PATIENT_KEY      NUMBER,
    DOCTOR_KEY       NUMBER,
    DEPT_KEY         NUMBER,
    DATE_KEY         NUMBER,
    APPOINTMENT_DATE DATE,
    STATUS           STRING,
    IS_VALID_RECORD  BOOLEAN,
    CREATED_BY       STRING DEFAULT CURRENT_USER(),
    CREATED_ON       TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- =============================================
-- 6. FACT_MEDICAL_RECORDS
-- =============================================
CREATE OR REPLACE TABLE FACT_MEDICAL_RECORDS (
    RECORD_KEY       NUMBER AUTOINCREMENT,
    RECORD_ID        STRING,
    PATIENT_KEY      NUMBER,
    RECORD_DATE      DATE,
    DIAGNOSIS        STRING,
    PROCEDURE_NAME   STRING,
    IS_VALID_RECORD  BOOLEAN,
    CREATED_BY       STRING DEFAULT CURRENT_USER(),
    CREATED_ON       TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- =============================================
-- 7. FACT_BILLING
-- =============================================
CREATE OR REPLACE TABLE FACT_BILLING (
    BILL_KEY         NUMBER AUTOINCREMENT,
    BILL_ID          STRING,
    PATIENT_KEY      NUMBER,
    APPOINTMENT_KEY  NUMBER,
    BILL_DATE        DATE,
    TOTAL_AMOUNT     NUMBER(12,2),
    PAID_AMOUNT      NUMBER(12,2),
    PAYMENT_STATUS   STRING,
    IS_VALID_RECORD  BOOLEAN,
    CREATED_BY       STRING DEFAULT CURRENT_USER(),
    CREATED_ON       TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

USE SCHEMA CURATED;

-- Clear existing data
TRUNCATE TABLE DIM_PATIENT;

-- MERGE for DIM_PATIENT with SCD Type 2
MERGE INTO DIM_PATIENT AS tgt
USING (
    SELECT 
        PATIENT_ID,
        NAME,
        DOB,
        GENDER,
        EMAIL,
        PHONE,
        CITY,
        STATE,
        CURRENT_DATE() AS LOAD_DATE,
        ROW_NUMBER() OVER (PARTITION BY PATIENT_ID ORDER BY CREATED_ON DESC) AS RN
    FROM VALIDATED.VALIDATED_PATIENTS
    WHERE IS_VALID_RECORD = TRUE
    QUALIFY RN = 1
) AS src
ON tgt.PATIENT_ID = src.PATIENT_ID AND tgt.IS_CURRENT = 'Y'

-- When matched and data changed, close the old record
WHEN MATCHED AND (
    tgt.NAME != src.NAME OR
    tgt.CITY != src.CITY OR
    tgt.STATE != src.STATE OR
    tgt.PHONE != src.PHONE OR
    tgt.EMAIL != src.EMAIL
) THEN UPDATE SET
    tgt.IS_CURRENT = 'N',
    tgt.VALID_TO = src.LOAD_DATE

-- Insert new record (for new patients or changed records)
WHEN NOT MATCHED THEN INSERT (
    PATIENT_ID, NAME, DOB, GENDER, EMAIL, PHONE, CITY, STATE,
    VALID_FROM, VALID_TO, IS_CURRENT, VERSION_NUMBER,
    CREATED_BY, CREATED_ON, SOURCE_TABLE
) VALUES (
    src.PATIENT_ID, src.NAME, src.DOB, src.GENDER, src.EMAIL, src.PHONE,
    src.CITY, src.STATE,
    src.LOAD_DATE, TO_DATE('9999-12-31'), 'Y',
    COALESCE((SELECT MAX(VERSION_NUMBER) + 1 FROM DIM_PATIENT WHERE PATIENT_ID = src.PATIENT_ID), 1),
    CURRENT_USER(), CURRENT_TIMESTAMP(), 'VALIDATED_PATIENTS'
);


USE SCHEMA CURATED;

-- Clear existing data
TRUNCATE TABLE DIM_DOCTOR;

-- MERGE for DIM_DOCTOR with SCD Type 2
MERGE INTO DIM_DOCTOR AS tgt
USING (
    SELECT DISTINCT
        DOCTOR_ID,
        DOCTOR_NAME,
        SPECIALIZATION,
        DEPARTMENT,
        CURRENT_DATE() AS LOAD_DATE
    FROM (
        SELECT 
            DOCTOR AS DOCTOR_ID,
            DOCTOR AS DOCTOR_NAME,
            DEPARTMENT AS SPECIALIZATION,
            DEPARTMENT,
            ROW_NUMBER() OVER (PARTITION BY DOCTOR ORDER BY CREATED_ON DESC) AS RN
        FROM VALIDATED.VALIDATED_APPOINTMENTS
        WHERE IS_VALID_RECORD = TRUE
    )
    WHERE RN = 1
) AS src
ON tgt.DOCTOR_ID = src.DOCTOR_ID AND tgt.IS_CURRENT = 'Y'

-- When matched and data changed, close the old record
WHEN MATCHED AND (
    tgt.DOCTOR_NAME != src.DOCTOR_NAME OR
    tgt.SPECIALIZATION != src.SPECIALIZATION OR
    tgt.DEPARTMENT != src.DEPARTMENT
) THEN UPDATE SET
    tgt.IS_CURRENT = 'N',
    tgt.VALID_TO = src.LOAD_DATE

-- Insert new record
WHEN NOT MATCHED THEN INSERT (
    DOCTOR_ID, DOCTOR_NAME, SPECIALIZATION, DEPARTMENT,
    VALID_FROM, VALID_TO, IS_CURRENT, VERSION_NUMBER,
    CREATED_BY, CREATED_ON, SOURCE_TABLE
) VALUES (
    src.DOCTOR_ID, src.DOCTOR_NAME, src.SPECIALIZATION, src.DEPARTMENT,
    src.LOAD_DATE, TO_DATE('9999-12-31'), 'Y',
    COALESCE((SELECT MAX(VERSION_NUMBER) + 1 FROM DIM_DOCTOR WHERE DOCTOR_ID = src.DOCTOR_ID), 1),
    CURRENT_USER(), CURRENT_TIMESTAMP(), 'VALIDATED_APPOINTMENTS'
);
USE SCHEMA CURATED;

-- Clear existing data
TRUNCATE TABLE DIM_DEPARTMENT;

-- MERGE for DIM_DEPARTMENT (Only from APPOINTMENTS)
MERGE INTO DIM_DEPARTMENT AS tgt
USING (
    SELECT DISTINCT
        UPPER(SUBSTR(DEPARTMENT, 1, 4)) AS DEPT_CODE,
        INITCAP(TRIM(DEPARTMENT)) AS DEPT_NAME
    FROM VALIDATED.VALIDATED_APPOINTMENTS
    WHERE DEPARTMENT IS NOT NULL 
      AND DEPARTMENT != ''
      AND IS_VALID_RECORD = TRUE
) AS src
ON tgt.DEPT_CODE = src.DEPT_CODE

WHEN MATCHED THEN UPDATE SET
    tgt.DEPT_NAME = src.DEPT_NAME,
    tgt.CREATED_BY = CURRENT_USER(),
    tgt.CREATED_ON = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN INSERT (
    DEPT_CODE, DEPT_NAME, CREATED_BY, CREATED_ON
) VALUES (
    src.DEPT_CODE, src.DEPT_NAME, CURRENT_USER(), CURRENT_TIMESTAMP()
);



USE SCHEMA CURATED;

-- Clear existing data
TRUNCATE TABLE FACT_APPOINTMENTS;

-- MERGE for FACT_APPOINTMENTS
MERGE INTO FACT_APPOINTMENTS AS tgt
USING (
    SELECT 
        vAPPT.APPOINTMENT_ID,
        vAPPT.PATIENT_ID,
        vAPPT.DOCTOR AS DOCTOR_ID,
        vAPPT.DEPARTMENT,
        vAPPT.APPOINTMENT_DATE,
        vAPPT.STATUS,
        vAPPT.IS_VALID_RECORD,
        
        -- Get surrogate keys from dimension tables
        dp.PATIENT_KEY,
        dd.DOCTOR_KEY,
        ddept.DEPT_KEY,
        NULL AS DATE_KEY  -- Will add later when DIM_DATE is loaded
        
    FROM VALIDATED.VALIDATED_APPOINTMENTS vAPPT
    LEFT JOIN CURATED.DIM_PATIENT dp 
        ON vAPPT.PATIENT_ID = dp.PATIENT_ID AND dp.IS_CURRENT = 'Y'
    LEFT JOIN CURATED.DIM_DOCTOR dd 
        ON vAPPT.DOCTOR = dd.DOCTOR_ID AND dd.IS_CURRENT = 'Y'
    LEFT JOIN CURATED.DIM_DEPARTMENT ddept 
        ON UPPER(SUBSTR(vAPPT.DEPARTMENT, 1, 4)) = ddept.DEPT_CODE
    WHERE vAPPT.IS_VALID_RECORD = TRUE
    
) AS src
ON tgt.APPOINTMENT_ID = src.APPOINTMENT_ID

WHEN MATCHED THEN UPDATE SET
    tgt.PATIENT_KEY = src.PATIENT_KEY,
    tgt.DOCTOR_KEY = src.DOCTOR_KEY,
    tgt.DEPT_KEY = src.DEPT_KEY,
    tgt.DATE_KEY = src.DATE_KEY,
    tgt.APPOINTMENT_DATE = src.APPOINTMENT_DATE,
    tgt.STATUS = src.STATUS,
    tgt.IS_VALID_RECORD = src.IS_VALID_RECORD,
    tgt.CREATED_BY = CURRENT_USER(),
    tgt.CREATED_ON = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN INSERT (
    APPOINTMENT_ID,
    PATIENT_KEY,
    DOCTOR_KEY,
    DEPT_KEY,
    DATE_KEY,
    APPOINTMENT_DATE,
    STATUS,
    IS_VALID_RECORD,
    CREATED_BY,
    CREATED_ON
) VALUES (
    src.APPOINTMENT_ID,
    src.PATIENT_KEY,
    src.DOCTOR_KEY,
    src.DEPT_KEY,
    src.DATE_KEY,
    src.APPOINTMENT_DATE,
    src.STATUS,
    src.IS_VALID_RECORD,
    CURRENT_USER(),
    CURRENT_TIMESTAMP()
);

USE SCHEMA CURATED;

-- Clear existing data
TRUNCATE TABLE FACT_MEDICAL_RECORDS;

-- MERGE for FACT_MEDICAL_RECORDS
MERGE INTO FACT_MEDICAL_RECORDS AS tgt
USING (
    SELECT 
        vREC.RECORD_ID,
        vREC.PATIENT_ID,
        vREC.RECORD_DATE,
        vREC.DIAGNOSIS,
        vREC.PROCEDURE AS PROCEDURE_NAME,
        vREC.IS_VALID_RECORD,
        
        -- Get surrogate keys from dimension tables
        dp.PATIENT_KEY
        
    FROM VALIDATED.VALIDATED_MEDICAL_RECORDS vREC
    LEFT JOIN CURATED.DIM_PATIENT dp 
        ON vREC.PATIENT_ID = dp.PATIENT_ID AND dp.IS_CURRENT = 'Y'
    WHERE vREC.IS_VALID_RECORD = TRUE
    
) AS src
ON tgt.RECORD_ID = src.RECORD_ID

WHEN MATCHED THEN UPDATE SET
    tgt.PATIENT_KEY = src.PATIENT_KEY,
    tgt.RECORD_DATE = src.RECORD_DATE,
    tgt.DIAGNOSIS = src.DIAGNOSIS,
    tgt.PROCEDURE_NAME = src.PROCEDURE_NAME,
    tgt.IS_VALID_RECORD = src.IS_VALID_RECORD,
    tgt.CREATED_BY = CURRENT_USER(),
    tgt.CREATED_ON = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN INSERT (
    RECORD_ID,
    PATIENT_KEY,
    RECORD_DATE,
    DIAGNOSIS,
    PROCEDURE_NAME,
    IS_VALID_RECORD,
    CREATED_BY,
    CREATED_ON
) VALUES (
    src.RECORD_ID,
    src.PATIENT_KEY,
    src.RECORD_DATE,
    src.DIAGNOSIS,
    src.PROCEDURE_NAME,
    src.IS_VALID_RECORD,
    CURRENT_USER(),
    CURRENT_TIMESTAMP()
);



USE SCHEMA CURATED;

-- Clear existing data
TRUNCATE TABLE FACT_BILLING;

-- MERGE for FACT_BILLING
MERGE INTO FACT_BILLING AS tgt
USING (
    SELECT 
        vBILL.BILL_ID,
        vBILL.PATIENT_ID,
        vBILL.APPOINTMENT_ID,
        vBILL.BILL_DATE,
        vBILL.TOTAL_AMOUNT,
        vBILL.PAID_AMOUNT,
        vBILL.PAYMENT_STATUS,
        vBILL.IS_VALID_RECORD,
        
        -- Get surrogate keys from dimension tables
        dp.PATIENT_KEY,
        fa.APPOINTMENT_KEY
        
    FROM VALIDATED.VALIDATED_BILLING vBILL
    LEFT JOIN CURATED.DIM_PATIENT dp 
        ON vBILL.PATIENT_ID = dp.PATIENT_ID AND dp.IS_CURRENT = 'Y'
    LEFT JOIN CURATED.FACT_APPOINTMENTS fa 
        ON vBILL.APPOINTMENT_ID = fa.APPOINTMENT_ID
    WHERE vBILL.IS_VALID_RECORD = TRUE
    
) AS src
ON tgt.BILL_ID = src.BILL_ID

WHEN MATCHED THEN UPDATE SET
    tgt.PATIENT_KEY = src.PATIENT_KEY,
    tgt.APPOINTMENT_KEY = src.APPOINTMENT_KEY,
    tgt.BILL_DATE = src.BILL_DATE,
    tgt.TOTAL_AMOUNT = src.TOTAL_AMOUNT,
    tgt.PAID_AMOUNT = src.PAID_AMOUNT,
    tgt.PAYMENT_STATUS = src.PAYMENT_STATUS,
    tgt.IS_VALID_RECORD = src.IS_VALID_RECORD,
    tgt.CREATED_BY = CURRENT_USER(),
    tgt.CREATED_ON = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN INSERT (
    BILL_ID,
    PATIENT_KEY,
    APPOINTMENT_KEY,
    BILL_DATE,
    TOTAL_AMOUNT,
    PAID_AMOUNT,
    PAYMENT_STATUS,
    IS_VALID_RECORD,
    CREATED_BY,
    CREATED_ON
) VALUES (
    src.BILL_ID,
    src.PATIENT_KEY,
    src.APPOINTMENT_KEY,
    src.BILL_DATE,
    src.TOTAL_AMOUNT,
    src.PAID_AMOUNT,
    src.PAYMENT_STATUS,
    src.IS_VALID_RECORD,
    CURRENT_USER(),
    CURRENT_TIMESTAMP()
);

SELECT 'DIM_PATIENT' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM DIM_PATIENT
UNION ALL
SELECT 'DIM_DOCTOR', COUNT(*) FROM DIM_DOCTOR
UNION ALL
SELECT 'DIM_DEPARTMENT', COUNT(*) FROM DIM_DEPARTMENT
UNION ALL
SELECT 'FACT_APPOINTMENTS', COUNT(*) FROM FACT_APPOINTMENTS
UNION ALL
SELECT 'FACT_MEDICAL_RECORDS', COUNT(*) FROM FACT_MEDICAL_RECORDS
UNION ALL
SELECT 'FACT_BILLING', COUNT(*) FROM FACT_BILLING;


-- =============================================================
-- STEP 1: USE DATABASE / SCHEMAS / WAREHOUSE
-- =============================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE SNOW_VALUT;
USE SCHEMA RAW;

-- =============================================================
-- STEP 2: CREATE STREAMS ON RAW TABLES
-- =============================================================

CREATE OR REPLACE STREAM STRM_RAW_PATIENTS
ON TABLE RAW.RAW_PATIENTS;

CREATE OR REPLACE STREAM STRM_RAW_APPOINTMENTS
ON TABLE RAW.RAW_APPOINTMENTS;

CREATE OR REPLACE STREAM STRM_RAW_MEDICAL_RECORDS
ON TABLE RAW.RAW_MEDICAL_RECORDS;

CREATE OR REPLACE STREAM STRM_RAW_BILLING
ON TABLE RAW.RAW_BILLING;

-- =============================================================
-- STEP 3: VERIFY STREAMS
-- =============================================================

SHOW STREAMS;

-- =============================================================
-- STEP 4: CREATE TASK FOR PATIENTS
-- =============================================================

CREATE OR REPLACE TASK TASK_VALIDATE_PATIENTS
WAREHOUSE = COMPUTE_WH
SCHEDULE = '10 seconds'
WHEN SYSTEM$STREAM_HAS_DATA('RAW.STRM_RAW_PATIENTS')
AS

MERGE INTO VALIDATED.VALIDATED_PATIENTS AS T
USING
(
    SELECT
        TRIM(PATIENT_ID) AS PATIENT_ID,
        INITCAP(TRIM(NAME)) AS NAME,
        TRY_TO_DATE(DOB) AS DOB,
        UPPER(TRIM(GENDER)) AS GENDER,
        LOWER(TRIM(EMAIL)) AS EMAIL,
        REGEXP_REPLACE(PHONE,'[^0-9]','') AS PHONE,
        INITCAP(TRIM(CITY)) AS CITY,
        UPPER(TRIM(STATE)) AS STATE,
        TRUE AS IS_VALID_RECORD,
        'AUTO_LOAD' AS VALIDATION_ERRORS,
        CURRENT_USER() AS CREATED_BY,
        CURRENT_TIMESTAMP() AS CREATED_ON
    FROM RAW.STRM_RAW_PATIENTS
) S
ON T.PATIENT_ID = S.PATIENT_ID

WHEN MATCHED THEN UPDATE SET
T.NAME = S.NAME,
T.DOB = S.DOB,
T.GENDER = S.GENDER,
T.EMAIL = S.EMAIL,
T.PHONE = S.PHONE,
T.CITY = S.CITY,
T.STATE = S.STATE,
T.IS_VALID_RECORD = TRUE,
T.VALIDATION_ERRORS = 'AUTO_UPDATED',
T.CREATED_ON = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN INSERT
(
PATIENT_ID, NAME, DOB, GENDER, EMAIL, PHONE, CITY, STATE,
IS_VALID_RECORD, VALIDATION_ERRORS, CREATED_BY, CREATED_ON
)
VALUES
(
S.PATIENT_ID, S.NAME, S.DOB, S.GENDER, S.EMAIL, S.PHONE, S.CITY, S.STATE,
S.IS_VALID_RECORD, S.VALIDATION_ERRORS, S.CREATED_BY, S.CREATED_ON
);


ALTER TASK TASK_VALIDATE_PATIENTS RESUME;



INSERT INTO RAW.RAW_PATIENTS
(
PATIENT_ID, NAME, DOB, GENDER, EMAIL, PHONE, CITY, STATE
)
VALUES
(
'P1101',
'New Patient',
'2000-01-01',
'FEMALE',
'newpatient@test.com',
'9876543210',
'Chennai',
'TN'
);

-- WAIT 10 sec MINUTES
-- THEN CHECK:

select * from raw.strm_raw_patients;

SELECT * FROM VALIDATED.VALIDATED_PATIENTS
WHERE PATIENT_ID = 'P1101';

show tasks;
-- =============================================================
-- STEP 5: CREATE TASK FOR APPOINTMENTS
-- =============================================================

CREATE OR REPLACE TASK TASK_VALIDATE_APPOINTMENTS
WAREHOUSE = COMPUTE_WH
SCHEDULE = '10 seconds'
WHEN SYSTEM$STREAM_HAS_DATA('RAW.STRM_RAW_APPOINTMENTS')
AS

MERGE INTO VALIDATED.VALIDATED_APPOINTMENTS AS T
USING
(
    SELECT
        TRIM(APPOINTMENT_ID) AS APPOINTMENT_ID,
        TRIM(PATIENT_ID) AS PATIENT_ID,
        INITCAP(TRIM(DOCTOR)) AS DOCTOR,
        INITCAP(TRIM(DEPARTMENT)) AS DEPARTMENT,
        TRY_TO_DATE(APPOINTMENT_DATE) AS APPOINTMENT_DATE,
        UPPER(TRIM(STATUS)) AS STATUS,
        TRUE AS IS_VALID_RECORD,
        'AUTO_LOAD' AS VALIDATION_ERRORS,
        CURRENT_USER() AS CREATED_BY,
        CURRENT_TIMESTAMP() AS CREATED_ON
    FROM RAW.STRM_RAW_APPOINTMENTS
) S
ON T.APPOINTMENT_ID = S.APPOINTMENT_ID

WHEN MATCHED THEN UPDATE SET
T.STATUS = S.STATUS,
T.APPOINTMENT_DATE = S.APPOINTMENT_DATE,
T.CREATED_ON = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN INSERT
(
APPOINTMENT_ID, PATIENT_ID, DOCTOR, DEPARTMENT, APPOINTMENT_DATE, STATUS,
IS_VALID_RECORD, VALIDATION_ERRORS, CREATED_BY, CREATED_ON
)
VALUES
(
S.APPOINTMENT_ID, S.PATIENT_ID, S.DOCTOR, S.DEPARTMENT, S.APPOINTMENT_DATE, S.STATUS,
S.IS_VALID_RECORD, S.VALIDATION_ERRORS, S.CREATED_BY, S.CREATED_ON
);

-- =============================================================
-- STEP 6: CREATE TASK FOR MEDICAL RECORDS
-- =============================================================

CREATE OR REPLACE TASK TASK_VALIDATE_MEDICAL
WAREHOUSE = COMPUTE_WH
SCHEDULE = '10 seconds'
WHEN SYSTEM$STREAM_HAS_DATA('RAW.STRM_RAW_MEDICAL_RECORDS')
AS

MERGE INTO VALIDATED.VALIDATED_MEDICAL_RECORDS AS T
USING
(
    SELECT
        TRIM(RECORD_ID) AS RECORD_ID,
        TRIM(PATIENT_ID) AS PATIENT_ID,
        TRY_TO_DATE(RECORD_DATE) AS RECORD_DATE,
        INITCAP(TRIM(DIAGNOSIS)) AS DIAGNOSIS,
        INITCAP(TRIM(PROCEDURE)) AS PROCEDURE,
        TRUE AS IS_VALID_RECORD,
        'AUTO_LOAD' AS VALIDATION_ERRORS,
        CURRENT_USER() AS CREATED_BY,
        CURRENT_TIMESTAMP() AS CREATED_ON
    FROM RAW.STRM_RAW_MEDICAL_RECORDS
) S
ON T.RECORD_ID = S.RECORD_ID

WHEN MATCHED THEN UPDATE SET
T.DIAGNOSIS = S.DIAGNOSIS,
T.PROCEDURE = S.PROCEDURE,
T.CREATED_ON = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN INSERT
(
RECORD_ID, PATIENT_ID, RECORD_DATE, DIAGNOSIS, PROCEDURE,
IS_VALID_RECORD, VALIDATION_ERRORS, CREATED_BY, CREATED_ON
)
VALUES
(
S.RECORD_ID, S.PATIENT_ID, S.RECORD_DATE, S.DIAGNOSIS, S.PROCEDURE,
S.IS_VALID_RECORD, S.VALIDATION_ERRORS, S.CREATED_BY, S.CREATED_ON
);

-- =============================================================
-- STEP 7: CREATE TASK FOR BILLING
-- =============================================================

CREATE OR REPLACE TASK TASK_VALIDATE_BILLING
WAREHOUSE = COMPUTE_WH
SCHEDULE = '10 seconds'
WHEN SYSTEM$STREAM_HAS_DATA('RAW.STRM_RAW_BILLING')
AS

MERGE INTO VALIDATED.VALIDATED_BILLING AS T
USING
(
    SELECT
        TRIM(BILL_ID) AS BILL_ID,
        TRIM(PATIENT_ID) AS PATIENT_ID,
        TRIM(APPOINTMENT_ID) AS APPOINTMENT_ID,
        TRY_TO_DATE(BILL_DATE) AS BILL_DATE,
        TRY_TO_NUMBER(REPLACE(TOTAL_AMOUNT,',','')) AS TOTAL_AMOUNT,
        TRY_TO_NUMBER(REPLACE(PAID_AMOUNT,',','')) AS PAID_AMOUNT,
        UPPER(TRIM(PAYMENT_STATUS)) AS PAYMENT_STATUS,
        TRUE AS IS_VALID_RECORD,
        'AUTO_LOAD' AS VALIDATION_ERRORS,
        CURRENT_USER() AS CREATED_BY,
        CURRENT_TIMESTAMP() AS CREATED_ON
    FROM RAW.STRM_RAW_BILLING
) S
ON T.BILL_ID = S.BILL_ID

WHEN MATCHED THEN UPDATE SET
T.TOTAL_AMOUNT = S.TOTAL_AMOUNT,
T.PAID_AMOUNT = S.PAID_AMOUNT,
T.PAYMENT_STATUS = S.PAYMENT_STATUS,
T.CREATED_ON = CURRENT_TIMESTAMP()

WHEN NOT MATCHED THEN INSERT
(
BILL_ID, PATIENT_ID, APPOINTMENT_ID, BILL_DATE, TOTAL_AMOUNT, PAID_AMOUNT, PAYMENT_STATUS,
IS_VALID_RECORD, VALIDATION_ERRORS, CREATED_BY, CREATED_ON
)
VALUES
(
S.BILL_ID, S.PATIENT_ID, S.APPOINTMENT_ID, S.BILL_DATE, S.TOTAL_AMOUNT, S.PAID_AMOUNT, S.PAYMENT_STATUS,
S.IS_VALID_RECORD, S.VALIDATION_ERRORS, S.CREATED_BY, S.CREATED_ON
);

-- =============================================================
-- STEP 8: RESUME ALL TASKS
-- =============================================================

ALTER TASK TASK_VALIDATE_PATIENTS RESUME;
ALTER TASK TASK_VALIDATE_APPOINTMENTS RESUME;
ALTER TASK TASK_VALIDATE_MEDICAL RESUME;
ALTER TASK TASK_VALIDATE_BILLING RESUME;

-- =============================================================
-- STEP 9: CHECK TASK STATUS
-- =============================================================

SHOW TASKS;

-- =============================================================
-- STEP 10: TEST AUTOMATION
-- INSERT NEW RAW DATA
-- =============================================================

INSERT INTO RAW.RAW_PATIENTS
(
PATIENT_ID, NAME, DOB, GENDER, EMAIL, PHONE, CITY, STATE
)
VALUES
(
'P999',
'New Patient',
'2000-01-01',
'FEMALE',
'newpatient@test.com',
'9876543210',
'Chennai',
'TN'
);

-- WAIT 10 sec MINUTES
-- THEN CHECK:


select * from raw.strm_raw_patients;

SELECT * FROM VALIDATED.VALIDATED_PATIENTS
WHERE PATIENT_ID = 'P999';


show tasks;

-- =====================================================
-- 3.medical_records
-- =====================================================
INSERT INTO RAW.RAW_MEDICAL_RECORDS
(
RECORD_ID, PATIENT_ID, RECORD_DATE, DIAGNOSIS, PROCEDURE
)
VALUES
(
'M1000',
'P999',
'2026-04-30',
'Chest Pain',
'ECG'
);

-- CHECK STREAM
SELECT * FROM RAW.STRM_RAW_MEDICAL_RECORDS;

-- WAIT 10 sec MINUTES THEN CHECK VALIDATED
SELECT *
FROM VALIDATED.VALIDATED_MEDICAL_RECORDS
WHERE RECORD_ID = 'M999';



-- =====================================================
-- 3. BILLING
-- =====================================================

INSERT INTO RAW.RAW_BILLING
(
BILL_ID, PATIENT_ID, APPOINTMENT_ID, BILL_DATE,
TOTAL_AMOUNT, PAID_AMOUNT, PAYMENT_STATUS
)
VALUES
(
'B999',
'P999',
'A999',
'2026-04-30',
'2500',
'1000',
'PARTIAL'
);

-- CHECK STREAM
SELECT * FROM RAW.STRM_RAW_BILLING;

-- WAIT 5 MINUTES THEN CHECK VALIDATED
SELECT *
FROM VALIDATED.VALIDATED_BILLING
WHERE BILL_ID = 'B999';

-- =============================================================
-- STEP 11: TASK HISTORY
-- =============================================================

SELECT *
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY());

-- =============================================================
-- END
-- =============================================================



USE DATABASE SNOW_VALUT;
USE SCHEMA VALIDATED;

CREATE OR REPLACE STREAM st_patients 
ON TABLE VALIDATED_PATIENTS;

CREATE OR REPLACE STREAM st_appointments 
ON TABLE VALIDATED_APPOINTMENTS;

CREATE OR REPLACE STREAM st_billing 
ON TABLE VALIDATED_BILLING;

CREATE OR REPLACE STREAM st_medical_records 
ON TABLE VALIDATED_MEDICAL_RECORDS;


USE DATABASE SNOW_VALUT;
USE SCHEMA CURATED;

CREATE OR REPLACE PROCEDURE SP_LOAD_CURATED()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN

-- =============================================
-- DIM_PATIENT (SCD TYPE 2)
-- =============================================

MERGE INTO DIM_PATIENT tgt
USING (
    SELECT *
    FROM VALIDATED.ST_PATIENTS
    WHERE METADATA$ACTION IN ('INSERT','UPDATE')
) src
ON tgt.PATIENT_ID = src.PATIENT_ID AND tgt.IS_CURRENT = 'Y'

WHEN MATCHED AND (
    tgt.NAME != src.NAME OR
    tgt.CITY != src.CITY OR
    tgt.STATE != src.STATE OR
    tgt.PHONE != src.PHONE OR
    tgt.EMAIL != src.EMAIL
)
THEN UPDATE SET
    tgt.IS_CURRENT = 'N',
    tgt.VALID_TO = CURRENT_DATE()

WHEN NOT MATCHED THEN INSERT (
    PATIENT_ID, NAME, DOB, GENDER, EMAIL, PHONE, CITY, STATE,
    VALID_FROM, VALID_TO, IS_CURRENT, VERSION_NUMBER,
    CREATED_BY, CREATED_ON, SOURCE_TABLE
)
VALUES (
    src.PATIENT_ID, src.NAME, src.DOB, src.GENDER, src.EMAIL, src.PHONE,
    src.CITY, src.STATE,
    CURRENT_DATE(), TO_DATE('9999-12-31'), 'Y',
    1,
    CURRENT_USER(), CURRENT_TIMESTAMP(), 'VALIDATED_PATIENTS'
);

-- =============================================
-- DIM_DOCTOR (SCD TYPE 2)
-- =============================================

MERGE INTO DIM_DOCTOR tgt
USING (
    SELECT DISTINCT
        DOCTOR AS DOCTOR_ID,
        DOCTOR AS DOCTOR_NAME,
        DEPARTMENT AS SPECIALIZATION,
        DEPARTMENT
    FROM VALIDATED.ST_APPOINTMENTS
    WHERE METADATA$ACTION IN ('INSERT','UPDATE')
) src
ON tgt.DOCTOR_ID = src.DOCTOR_ID AND tgt.IS_CURRENT = 'Y'

WHEN MATCHED AND (
    tgt.DOCTOR_NAME != src.DOCTOR_NAME OR
    tgt.SPECIALIZATION != src.SPECIALIZATION OR
    tgt.DEPARTMENT != src.DEPARTMENT
)
THEN UPDATE SET
    tgt.IS_CURRENT = 'N',
    tgt.VALID_TO = CURRENT_DATE()

WHEN NOT MATCHED THEN INSERT (
    DOCTOR_ID, DOCTOR_NAME, SPECIALIZATION, DEPARTMENT,
    VALID_FROM, VALID_TO, IS_CURRENT, VERSION_NUMBER,
    CREATED_BY, CREATED_ON, SOURCE_TABLE
)
VALUES (
    src.DOCTOR_ID, src.DOCTOR_NAME, src.SPECIALIZATION, src.DEPARTMENT,
    CURRENT_DATE(), TO_DATE('9999-12-31'), 'Y',
    1,
    CURRENT_USER(), CURRENT_TIMESTAMP(), 'VALIDATED_APPOINTMENTS'
);

-- =============================================
-- DIM_DEPARTMENT
-- =============================================

MERGE INTO DIM_DEPARTMENT tgt
USING (
    SELECT DISTINCT
        UPPER(SUBSTR(DEPARTMENT,1,4)) AS DEPT_CODE,
        INITCAP(DEPARTMENT) AS DEPT_NAME
    FROM VALIDATED.ST_APPOINTMENTS
    WHERE METADATA$ACTION IN ('INSERT','UPDATE')
) src
ON tgt.DEPT_CODE = src.DEPT_CODE

WHEN MATCHED THEN UPDATE SET
    tgt.DEPT_NAME = src.DEPT_NAME

WHEN NOT MATCHED THEN INSERT (
    DEPT_CODE, DEPT_NAME, CREATED_BY, CREATED_ON
)
VALUES (
    src.DEPT_CODE, src.DEPT_NAME, CURRENT_USER(), CURRENT_TIMESTAMP()
);

-- =============================================
-- FACT_APPOINTMENTS
-- =============================================

MERGE INTO FACT_APPOINTMENTS tgt
USING (
    SELECT 
        A.APPOINTMENT_ID,
        dp.PATIENT_KEY,
        dd.DOCTOR_KEY,
        dpt.DEPT_KEY,
        A.APPOINTMENT_DATE,
        A.STATUS,
        A.IS_VALID_RECORD
    FROM VALIDATED.ST_APPOINTMENTS A
    LEFT JOIN DIM_PATIENT dp 
        ON A.PATIENT_ID = dp.PATIENT_ID AND dp.IS_CURRENT = 'Y'
    LEFT JOIN DIM_DOCTOR dd 
        ON A.DOCTOR = dd.DOCTOR_ID AND dd.IS_CURRENT = 'Y'
    LEFT JOIN DIM_DEPARTMENT dpt 
        ON UPPER(SUBSTR(A.DEPARTMENT,1,4)) = dpt.DEPT_CODE
    WHERE METADATA$ACTION IN ('INSERT','UPDATE')
) src
ON tgt.APPOINTMENT_ID = src.APPOINTMENT_ID

WHEN MATCHED THEN UPDATE SET
    tgt.PATIENT_KEY = src.PATIENT_KEY,
    tgt.DOCTOR_KEY = src.DOCTOR_KEY,
    tgt.DEPT_KEY = src.DEPT_KEY,
    tgt.APPOINTMENT_DATE = src.APPOINTMENT_DATE,
    tgt.STATUS = src.STATUS,
    tgt.IS_VALID_RECORD = src.IS_VALID_RECORD

WHEN NOT MATCHED THEN INSERT (
    APPOINTMENT_ID, PATIENT_KEY, DOCTOR_KEY, DEPT_KEY,
    APPOINTMENT_DATE, STATUS, IS_VALID_RECORD,
    CREATED_BY, CREATED_ON
)
VALUES (
    src.APPOINTMENT_ID, src.PATIENT_KEY, src.DOCTOR_KEY, src.DEPT_KEY,
    src.APPOINTMENT_DATE, src.STATUS, src.IS_VALID_RECORD,
    CURRENT_USER(), CURRENT_TIMESTAMP()
);

-- =============================================
-- FACT_MEDICAL_RECORDS
-- =============================================

MERGE INTO FACT_MEDICAL_RECORDS tgt
USING (
    SELECT 
        M.RECORD_ID,
        dp.PATIENT_KEY,
        M.RECORD_DATE,
        M.DIAGNOSIS,
        M.PROCEDURE AS PROCEDURE_NAME,
        M.IS_VALID_RECORD
    FROM VALIDATED.ST_MEDICAL_RECORDS M
    LEFT JOIN DIM_PATIENT dp 
        ON M.PATIENT_ID = dp.PATIENT_ID AND dp.IS_CURRENT = 'Y'
    WHERE METADATA$ACTION IN ('INSERT','UPDATE')
) src
ON tgt.RECORD_ID = src.RECORD_ID

WHEN MATCHED THEN UPDATE SET
    tgt.PATIENT_KEY = src.PATIENT_KEY,
    tgt.RECORD_DATE = src.RECORD_DATE,
    tgt.DIAGNOSIS = src.DIAGNOSIS,
    tgt.PROCEDURE_NAME = src.PROCEDURE_NAME,
    tgt.IS_VALID_RECORD = src.IS_VALID_RECORD

WHEN NOT MATCHED THEN INSERT (
    RECORD_ID, PATIENT_KEY, RECORD_DATE,
    DIAGNOSIS, PROCEDURE_NAME, IS_VALID_RECORD,
    CREATED_BY, CREATED_ON
)
VALUES (
    src.RECORD_ID, src.PATIENT_KEY, src.RECORD_DATE,
    src.DIAGNOSIS, src.PROCEDURE_NAME, src.IS_VALID_RECORD,
    CURRENT_USER(), CURRENT_TIMESTAMP()
);

-- =============================================
-- FACT_BILLING
-- =============================================

MERGE INTO FACT_BILLING tgt
USING (
    SELECT 
        B.BILL_ID,
        dp.PATIENT_KEY,
        fa.APPOINTMENT_KEY,
        B.BILL_DATE,
        B.TOTAL_AMOUNT,
        B.PAID_AMOUNT,
        B.PAYMENT_STATUS,
        B.IS_VALID_RECORD
    FROM VALIDATED.ST_BILLING B
    LEFT JOIN DIM_PATIENT dp 
        ON B.PATIENT_ID = dp.PATIENT_ID AND dp.IS_CURRENT = 'Y'
    LEFT JOIN FACT_APPOINTMENTS fa 
        ON B.APPOINTMENT_ID = fa.APPOINTMENT_ID
    WHERE METADATA$ACTION IN ('INSERT','UPDATE')
) src
ON tgt.BILL_ID = src.BILL_ID

WHEN MATCHED THEN UPDATE SET
    tgt.PATIENT_KEY = src.PATIENT_KEY,
    tgt.APPOINTMENT_KEY = src.APPOINTMENT_KEY,
    tgt.BILL_DATE = src.BILL_DATE,
    tgt.TOTAL_AMOUNT = src.TOTAL_AMOUNT,
    tgt.PAID_AMOUNT = src.PAID_AMOUNT,
    tgt.PAYMENT_STATUS = src.PAYMENT_STATUS,
    tgt.IS_VALID_RECORD = src.IS_VALID_RECORD

WHEN NOT MATCHED THEN INSERT (
    BILL_ID, PATIENT_KEY, APPOINTMENT_KEY,
    BILL_DATE, TOTAL_AMOUNT, PAID_AMOUNT,
    PAYMENT_STATUS, IS_VALID_RECORD,
    CREATED_BY, CREATED_ON
)
VALUES (
    src.BILL_ID, src.PATIENT_KEY, src.APPOINTMENT_KEY,
    src.BILL_DATE, src.TOTAL_AMOUNT, src.PAID_AMOUNT,
    src.PAYMENT_STATUS, src.IS_VALID_RECORD,
    CURRENT_USER(), CURRENT_TIMESTAMP()
);

RETURN 'SUCCESS';

END;
$$;



USE SCHEMA TASKS;

CREATE OR REPLACE TASK TASK_VALIDATED_TO_CURATED
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN
    SYSTEM$STREAM_HAS_DATA('SNOW_VALUT.VALIDATED.ST_PATIENTS')
 OR SYSTEM$STREAM_HAS_DATA('SNOW_VALUT.VALIDATED.ST_APPOINTMENTS')
 OR SYSTEM$STREAM_HAS_DATA('SNOW_VALUT.VALIDATED.ST_MEDICAL_RECORDS')
 OR SYSTEM$STREAM_HAS_DATA('SNOW_VALUT.VALIDATED.ST_BILLING')
AS
CALL CURATED.SP_LOAD_CURATED();

ALTER TASK TASK_VALIDATED_TO_CURATED RESUME;


SELECT *
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY())
WHERE NAME = 'TASK_VALIDATED_TO_CURATED'
ORDER BY SCHEDULED_TIME DESC;

INSERT INTO VALIDATED.VALIDATED_PATIENTS
VALUES (
    'P_TESTT',
    'TEST USER',
    '1995-01-01',
    'M',
    'test@mail.com',
    '9999999999',
    'CHENNAI',
    'TN',
    TRUE,
    'VALID',
    'SYS',
    CURRENT_TIMESTAMP()
);

SELECT SYSTEM$STREAM_HAS_DATA('SNOW_VALUT.VALIDATED.ST_PATIENTS');

SELECT *
FROM CURATED.DIM_PATIENT
WHERE PATIENT_ID = 'P_TESTT';

SELECT *
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY())
WHERE NAME = 'TASK_VALIDATED_TO_CURATED';


USE DATABASE SNOW_VALUT;
USE SCHEMA ANALYTICAL;

CREATE OR REPLACE VIEW VW_PATIENT_360 AS
SELECT 
    dp.PATIENT_ID,
    dp.NAME,
    dp.GENDER,
    dp.CITY,
    COUNT(DISTINCT fa.APPOINTMENT_ID) AS TOTAL_APPOINTMENTS,
    COUNT(DISTINCT fmr.RECORD_ID) AS TOTAL_RECORDS,
    SUM(fb.TOTAL_AMOUNT) AS TOTAL_BILL,
    SUM(fb.PAID_AMOUNT) AS TOTAL_PAID
FROM CURATED.DIM_PATIENT dp
LEFT JOIN CURATED.FACT_APPOINTMENTS fa 
    ON dp.PATIENT_KEY = fa.PATIENT_KEY
LEFT JOIN CURATED.FACT_MEDICAL_RECORDS fmr 
    ON dp.PATIENT_KEY = fmr.PATIENT_KEY
LEFT JOIN CURATED.FACT_BILLING fb 
    ON dp.PATIENT_KEY = fb.PATIENT_KEY
WHERE dp.IS_CURRENT = 'Y'
GROUP BY dp.PATIENT_ID, dp.NAME, dp.GENDER, dp.CITY;

CREATE OR REPLACE VIEW VW_PATIENT_RISK AS
SELECT 
    dp.PATIENT_ID,
    dp.NAME,
    COUNT(fmr.RECORD_ID) AS MEDICAL_HISTORY,
    
    CASE 
        WHEN COUNT(fmr.RECORD_ID) > 5 THEN 'HIGH RISK'
        WHEN COUNT(fmr.RECORD_ID) BETWEEN 2 AND 5 THEN 'MEDIUM RISK'
        ELSE 'LOW RISK'
    END AS RISK_LEVEL
FROM CURATED.DIM_PATIENT dp
LEFT JOIN CURATED.FACT_MEDICAL_RECORDS fmr 
    ON dp.PATIENT_KEY = fmr.PATIENT_KEY
WHERE dp.IS_CURRENT = 'Y'
GROUP BY dp.PATIENT_ID, dp.NAME;

CREATE OR REPLACE VIEW VW_REVENUE_TRENDS AS
SELECT 
    DATE_TRUNC('MONTH', BILL_DATE) AS MONTH,
    SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE,
    SUM(PAID_AMOUNT) AS TOTAL_PAID
FROM CURATED.FACT_BILLING
GROUP BY DATE_TRUNC('MONTH', BILL_DATE);

CREATE OR REPLACE VIEW VW_NO_SHOW_ANALYSIS AS
SELECT 
    STATUS,
    COUNT(*) AS TOTAL,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (), 2) AS PERCENTAGE
FROM CURATED.FACT_APPOINTMENTS
GROUP BY STATUS;

SELECT * FROM ANALYTICAL.VW_PATIENT_360;
SELECT * FROM ANALYTICAL.VW_PATIENT_RISK WHERE RISK_LEVEL='MEDIUM RISK';
SELECT * FROM ANALYTICAL.VW_REVENUE_TRENDS;
SELECT * FROM ANALYTICAL.VW_NO_SHOW_ANALYSIS;

DROP ANALYTICAL.VW_PATIENT_360






CREATE OR REPLACE VIEW ANALYTICAL.VW_PATIENT_360 AS
SELECT 
    dp.PATIENT_ID,
    dp.NAME,
    dp.GENDER,
    dp.CITY,

    COALESCE(fa.TOTAL_APPOINTMENTS, 0) AS TOTAL_APPOINTMENTS,
    COALESCE(fmr.TOTAL_RECORDS, 0) AS TOTAL_RECORDS,
    COALESCE(fb.TOTAL_BILL, 0) AS TOTAL_BILL,
    COALESCE(fb.TOTAL_PAID, 0) AS TOTAL_PAID

FROM CURATED.DIM_PATIENT dp

-- ✅ APPOINTMENTS (DEDUP + SAFE)
LEFT JOIN (
    SELECT 
        PATIENT_KEY,
        COUNT(DISTINCT APPOINTMENT_ID) AS TOTAL_APPOINTMENTS
    FROM CURATED.FACT_APPOINTMENTS
    WHERE IS_VALID_RECORD = TRUE
      AND PATIENT_KEY IS NOT NULL
    GROUP BY PATIENT_KEY
) fa 
ON dp.PATIENT_KEY = fa.PATIENT_KEY

-- ✅ MEDICAL RECORDS
LEFT JOIN (
    SELECT 
        PATIENT_KEY,
        COUNT(DISTINCT RECORD_ID) AS TOTAL_RECORDS
    FROM CURATED.FACT_MEDICAL_RECORDS
    WHERE IS_VALID_RECORD = TRUE
      AND PATIENT_KEY IS NOT NULL
    GROUP BY PATIENT_KEY
) fmr 
ON dp.PATIENT_KEY = fmr.PATIENT_KEY

-- ✅ BILLING (FIX NEGATIVE + NULL)
LEFT JOIN (
    SELECT 
        PATIENT_KEY,
        SUM(
            CASE 
                WHEN TOTAL_AMOUNT IS NULL OR TOTAL_AMOUNT < 0 THEN 0 
                ELSE TOTAL_AMOUNT 
            END
        ) AS TOTAL_BILL,

        SUM(
Selection deleted

            CASE 
                WHEN PAID_AMOUNT IS NULL OR PAID_AMOUNT < 0 THEN 0 
                ELSE PAID_AMOUNT 
            END
        ) AS TOTAL_PAID

    FROM CURATED.FACT_BILLING
    WHERE IS_VALID_RECORD = TRUE
      AND PATIENT_KEY IS NOT NULL
    GROUP BY PATIENT_KEY
) fb 
ON dp.PATIENT_KEY = fb.PATIENT_KEY

WHERE dp.IS_CURRENT = 'Y';

select * from ANALYTICAL.VW_PATIENT_360



SELECT * FROM ANALYTICAL.VW_NO_SHOW_ANALYSIS;

SELECT * From VW_PATIENT_360
WHERE CITY='Hyderabad'